### PR TITLE
(BKR-570) Errors in teardown do not obscure errors in test

### PR DESCRIPTION
**Pull request by samwoods1**
merge https://github.com/puppetlabs/beaker/pull/1187 first and I'll re-base to fix this.

### CODE REVIEW

**Comment by samwoods1** [comment]
Hmm.. yeah, this is failing because it has a dependency on https://github.com/puppetlabs/beaker/pull/1187.

**Comment by kevpl** [comment]
@samwoods1 #1187 merged!

**Comment by samwoods1** [comment]
@ki cool, rebased this one.

**Comment by samwoods1** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
