### PR TITLE
(BKR-1168) beaker version causes error output

### PR DESCRIPTION
**Pull request by raffs**
The issue was happening because beaker will run the function that needs the HOSTS array, which is define as null when running beaker --version, therefore ruby thrown _noMethod for nilClass_.

This commit add an expression to return the code when using **--version** option, instead of continuing running the beaker code.

### CODE REVIEW

**Comment by raffs** [comment]
@kevpl as we talked on the other PR, I create another branch and cherry-pick the commits from the previous PR related to this issue/ticket. Please let me know about anything else. 

Previous PR: https://github.com/puppetlabs/beaker/pull/1454

**Comment by kevpl** [comment]
@raffs thanks for fixing this up! Please add a spec test to make sure that we don't break this in the future, & we'll make sure this gets in soon!

**Comment by mchllweeks** [comment]
last comment still current

**Comment by kevpl** [comment]
@raffs it looks like a bunch of commits have been added to this PR, I'm having trouble seeing if any of them are the tests we're looking for. Since that's the case, we'll treat this as if it hasn't been updated:

Last comment is still current. If no progress is made on this in a week, we'll close it due to inactivity.

**Comment by ferglor** [comment]
Closing due to inactivity

**Pull request closed without merging**
