### PR TITLE
(BKR-395) Calling `remove_defaults_on` twice with `type: aio` in...

### PR DESCRIPTION
**Pull request by anodelman**
...config file throws exception

- ensure that we don't blow away the PATH and break the world

### CODE REVIEW

**Comment by anodelman** [comment]
Test failure unrelated to patch.

**Comment by anodelman** [comment]
retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
(of course I wait until just now to think of this), I thought we'd gotten rid of the `aio` type in #902?

Why is it here?

**Comment by anodelman** [comment]
@kevpl we still have the aio type because people are using it, so we still support it.  Now you can run in a mix of foss-aio and pe-aio and git-aio and everything is awesome!

**Pull request merged**
