### PR TITLE
(BKR-776) test case methods for exporting structured data to junit xml

### PR DESCRIPTION
**Pull request by er0ck**
to properly test this we need a pre-suite for beaker acceptance that runs beaker on the SUT so we can check its output.  will file in another ticket

### CODE REVIEW

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by er0ck** [comment]
@kevpl FYI:
just windows2008 failed in puppet-pkg acceptance tests due to infra issues:
```
Errored Tests Cases:
  Test Case /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-puppet-vpool-puppet-pkg/agent/windows2008r2/master/centos7/acceptance/pre_suite/puppet_pkg/install.rb reported: #<Beaker::Host::CommandFailure: Host 'kwwz8cxmgcc2u0f.delivery.puppetlabs.net' exited with 7 running:
 curl -o "C:\Windows\TEMP\puppet-3.8.1-x64.msi" -O http://downloads.puppetlabs.com/windows/puppet-3.8.1-x64.msi
Last 10 lines of output were:
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	
	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to downloads.puppetlabs.com port 80: Network is unreachable>
Skipped Tests Cases:
```

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by er0ck** [comment]
no idea.  centos7 only.  seems unrelated.
```
Errored Tests Cases:
      Test Case /var/lib/jenkins/workspace/qe_beaker_intn-sys-pe_upgrade-vpool/layout/64mdac-64a/platform/centos6/pe_acceptance_tests/acceptance/tests/pe_checks/spot_check_lm.rb reported: #<JSON::ParserError: 757: unexpected token at 'No server available'>
```

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
