### PR TITLE
(BKR-1168) Fix the `beaker --version` undefined method `each_key' for nil:NilClass

### PR DESCRIPTION
**Pull request by raffs**
The issue was happing because beaker will run the function that needs
the HOSTS arrays, which is defined as null when running `beaker --version`,
therefore ruby thrown noMethod for nilClass.

This commit add an expression to return the code when using '--version'
option, instead of continuing running the beaker code.

### CODE REVIEW

**Comment by ferglor** [comment]
@puppetlabs-jenkins test this please

**Comment by ericwilliamson** [comment]
👍 once CI passes

```
[17:58:06][ericwilliamson@Erics-MBP.corp.puppetlabs.net][/s/beaker]$ be beaker --version                                                                                                                                                                       [pr/1454][2.3.1]
      wWWWw
      |o o|
      | O |  3.23.0!
      |(")|
     / \X/ \
    |   V   |
    |   |   |
Beaker completed successfully, thanks.

[17:59:27][ericwilliamson@Erics-MBP.corp.puppetlabs.net][/s/beaker]$ gco master                                                                                                                                                                                [pr/1454][2.3.1]
Switched to branch 'master'
Your branch is up-to-date with 'puppetlabs/master'.

[17:59:34][ericwilliamson@Erics-MBP.corp.puppetlabs.net][/s/beaker]$ be beaker --version                                                                                                                                                                        [master][2.3.1]
      wWWWw
      |o o|
      | O |  3.24.0!
      |(")|
     / \X/ \
    |   V   |
    |   |   |
Failed: errored in CLI.initialize_network_manager
#<NoMethodError: undefined method `each_key' for nil:NilClass>
/s/beaker/bin/beaker:9
/Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30
/Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22
/Users/ericwilliamson/.rbenv/versions/2.3.1/bin/bundle:23
/Users/ericwilliamson/.rbenv/versions/2.3.1/bin/bundle:23
Failed: errored in CLI.provision
#<NoMethodError: undefined method `each_key' for nil:NilClass>
/s/beaker/bin/beaker:9
/Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30
/Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22
/Users/ericwilliamson/.rbenv/versions/2.3.1/bin/bundle:23
/Users/ericwilliamson/.rbenv/versions/2.3.1/bin/bundle:23
bundler: failed to load command: beaker (/Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/beaker)
NoMethodError: undefined method `each_key' for nil:NilClass
  /s/beaker/lib/beaker/network_manager.rb:58:in `provision'
  /s/beaker/lib/beaker/cli.rb:93:in `initialize_network_manager'
  /s/beaker/lib/beaker/cli.rb:79:in `provision'
  /s/beaker/bin/beaker:9:in `<top (required)>'
  /Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/beaker:23:in `load'
  /Users/ericwilliamson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/beaker:23:in `<top (required)>'
```

**Comment by ferglor** [comment]
Jenkins, test this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Comment by mchllweeks** [comment]
retest this please

**Comment by mchllweeks** [comment]
@raffs We have updated our contributing standards: [CONTRIBUTING.md](CONTRIBUTING.md).

Please add an entry in the [CHANGELOG.md](CHANGELOG.md) as another commit and I will merge this PR for our next release.

**Comment by raffs** [comment]
Excellent, I will do. Thanks for the heads up. 


Regards,

**Comment by tvpartytonight** [comment]
@raffs do you mind rebasing this PR so that the extra commits from other contributors don't show up in the commits to merge list?

**Comment by raffs** [comment]
Sure, I don’t mind at all. I will rebase it.

**Comment by raffs** [comment]
@tvpartytonight I rebased my branch and pushed the code into the repository. Please let me know about anything else, I needed to do.

**Comment by kevpl** [comment]
@raffs it looks like the rebase has gone astray here, as there are still 20 commits listed for what should be a fairly small change. I see that there are some merge & other types of commits as well. You'll have to clean this up for us to be able to look at it further.

If you'd rather just start clean, you can feel free to create a new branch/PR & cherry-pick the commits you want, closing this one out for that one. Or if you'd like to debug getting the logs corrected here, we're down to help as well.

**Comment by raffs** [comment]
@kevpl the clean PR with the cherry-pick sounds like a good plan. I will do that and let you know.

**Pull request closed without merging**
