### PR TITLE
add el8 support

### PR DESCRIPTION
**Pull request by florianfa**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Created https://tickets.puppetlabs.com/browse/BKR-1632 for this PR.

Please merge, it works!

**Comment by gimmyxd** [comment]
@puppetlabs-jenkins retest this please

**Comment by gimmyxd** [comment]
👍 looks good
@florianfa can you amend the commit message with the ticket created? tickets.puppetlabs.com/browse/BKR-1632

**Comment by florianfa** [comment]
@gimmyxd added the ticket number to the commit message

**Comment by genebean** [comment]
We are planning a gem release next Thursday @ghoneycutt

**Comment by ghoneycutt** [comment]
Thank you!

**Pull request merged**
