### PR TITLE
(PE-27037) Add redhatfips as recognized platform

### PR DESCRIPTION
**Pull request by nmburgan**
This adds the redhatfips platform to the recognized platform list.

### CODE REVIEW

**Comment by nmburgan** [comment]
Should be merged with https://github.com/puppetlabs/beaker-hostgenerator/pull/162

**Comment by jpartlow** [comment]
:+1:

**Comment by jpartlow** [comment]
Bundle install problem in inifile module tests: https://jenkins-sre.delivery.puppetlabs.net/job/sre_beaker_integration-system_rspec-module_inifile_master/106/LAYOUT=ubuntu1604-64mdac-64a,LDAP_TYPE=default,SAUCE=default,UNEEDED=UNEEDED,label=beaker/console

```
11:50:54 HEAD is now at 3739058... Merge pull request #229 from puppetlabs/hunner_msync
11:50:54 + '[' beaker == beaker-pe ']'
11:50:54 + bundle install --path vendor/bundle
11:50:54 Fetching gem metadata from https://artifactory.delivery.puppetlabs.net/artifactory/api/gems/rubygems/...........
11:50:58 Resolving dependencies...
11:50:58 Bundler could not find compatible versions for gem "beaker":
11:50:58   In Gemfile:
11:50:58     beaker-module_install_helper was resolved to 0.1.6, which depends on
11:50:58       beaker (~> 2.0)
11:50:58 
11:50:58     beaker-rspec was resolved to 6.2.4, which depends on
11:50:58       beaker (> 3.0)
11:50:58 
11:50:58 Bundler could not find compatible versions for gem "net-ssh":
11:50:58   In Gemfile:
11:50:58     beaker was resolved to 4.11.1, which depends on
11:50:58       net-ssh (~> 5.0)
11:50:58 
11:50:58 Could not find gem 'net-ssh (~> 5.0)', which is required by gem 'beaker', in any
11:50:58 of the sources.
```

**Comment by nmburgan** [comment]
That acceptance test failure looks like a problem with the test that is checking out a really old version of puppetlabs-inifile for some reason.

**Comment by jpartlow** [comment]
Could be a backwards compatibility check? @kevpl I think we'll need your help here ^

**Comment by kevpl** [comment]
retest this please

**Pull request merged**
