### PR TITLE
(MAINT) Fix indentation

### PR DESCRIPTION
**Pull request by petems**
Moved from #666 into it's own PR

### CODE REVIEW

**Comment by anodelman** [comment]
Needs a rebase.

**Comment by petems** [comment]
@anodelman Fixed :+1:

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
Broke spec somehow:

```

  1) ClassMixedWithDSLInstallUtils configure_puppet_on on windows it sets the puppet.conf file to the provided config
     Failure/Error: expect(command.args).to eq(" -ExecutionPolicy Bypass -InputFormat None -NoLogo -NoProfile -NonInteractive -Command \"$text = \\\"[main]`nserver=testbox.test.local`n`n\\\"; Set-Content -path '`cygpath -smF 35`/PuppetLabs/puppet/etc\\puppet.conf' -value $text\"")
       
       expected: " -ExecutionPolicy Bypass -InputFormat None -NoLogo -NoProfile -NonInteractive -Command \"$text = \\\"[main]`nserver=testbox.test.local`n`n\\\"; Set-Content -path '`cygpath -smF 35`/PuppetLabs/puppet/etc\\puppet.conf' -value $text\""
            got: ["-ExecutionPolicy", "Bypass", "-InputFormat", "None", "-NoLogo", "-NoProfile", "-NonInteractive", "-Command", "\"$text", "=", "\\\"[main]`nserver=testbox.test.local`n`n\\\";", "Set-Content", "-path", "'`cygpath", "-smF", "35`/PuppetLabs/puppet/etc\\puppet.conf'", "-value", "$text\""]
       
       (compared using ==)
     # ./spec/beaker/dsl/install_utils_spec.rb:602:in `block (5 levels) in <top (required)>'
     # ./lib/beaker/dsl/install_utils.rb:770:in `configure_puppet_on'
     # ./spec/beaker/dsl/install_utils_spec.rb:604:in `block (4 levels) in <top (required)>'

  2) ClassMixedWithDSLInstallUtils configure_puppet on windows it sets the puppet.conf file to the provided config
     Failure/Error: expect(command.args).to eq(" -ExecutionPolicy Bypass -InputFormat None -NoLogo -NoProfile -NonInteractive -Command \"$text = \\\"[main]`nserver=testbox.test.local`n`n\\\"; Set-Content -path '`cygpath -smF 35`/PuppetLabs/puppet/etc\\puppet.conf' -value $text\"")
       
       expected: " -ExecutionPolicy Bypass -InputFormat None -NoLogo -NoProfile -NonInteractive -Command \"$text = \\\"[main]`nserver=testbox.test.local`n`n\\\"; Set-Content -path '`cygpath -smF 35`/PuppetLabs/puppet/etc\\puppet.conf' -value $text\""
            got: ["-ExecutionPolicy", "Bypass", "-InputFormat", "None", "-NoLogo", "-NoProfile", "-NonInteractive", "-Command", "\"$text", "=", "\\\"[main]`nserver=testbox.test.local`n`n\\\";", "Set-Content", "-path", "'`cygpath", "-smF", "35`/PuppetLabs/puppet/etc\\puppet.conf'", "-value", "$text\""]
       
       (compared using ==)
     # ./spec/beaker/dsl/install_utils_spec.rb:632:in `block (5 levels) in <top (required)>'
     # ./lib/beaker/dsl/install_utils.rb:770:in `configure_puppet_on'
     # ./lib/beaker/dsl/install_utils.rb:731:in `block in configure_puppet'
     # ./lib/beaker/dsl/install_utils.rb:730:in `each'
     # ./lib/beaker/dsl/install_utils.rb:730:in `configure_puppet'
     # ./spec/beaker/dsl/install_utils_spec.rb:634:in `block (4 levels) in <top (required)>'

1 deprecation warning total

Finished in 11.25 seconds (files took 1.81 seconds to load)
797 examples, 2 failures

Failed examples:

rspec ./spec/beaker/dsl/install_utils_spec.rb:598 # ClassMixedWithDSLInstallUtils configure_puppet_on on windows it sets the puppet.conf file to the provided config
rspec ./spec/beaker/dsl/install_utils_spec.rb:628 # ClassMixedWithDSLInstallUtils configure_puppet on windows it sets the puppet.conf file to the provided config
```

**Comment by anodelman** [comment]
Sorry, not your spec failure.  Will retest.

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
Known debian 7 foss failure.

**Pull request merged**
