### PR TITLE
(BKR-671) - Add error handing for Beaker failing to acquire a VM from vmpooler

### PR DESCRIPTION
**Pull request by pinkypie**
The issue is when one of the specified host cannot be acquired.
Raise an error and attempt again until timeout (the same as with other provisioning errors).

### CODE REVIEW

**Comment by kevpl** [comment]
@pinkypie please add a spec test so that we don't break this in the future

**Comment by pinkypie** [comment]
@kevpl trying to. Having problems with getting the method to return an error in the spec test.

**Comment by rick** [comment]
It could be that wrapping some part of the `parsed_response[h['template']]` bit in a helper method would (a) give us a more intention-revealing name, and (b) make this easier to test.

**Comment by pinkypie** [comment]
Thanks @rick , could also probably do that for some of the other error handling logic in the provision method, and then add some more tests. Will make a note.

**Comment by kevpl** [comment]
@rick look good?

**Comment by rick** [comment]
:+1:

**Pull request merged**
