### PR TITLE
(BKR-516) Lookup more openstack credentials from ENV

### PR DESCRIPTION
**Pull request by maage**
Add support to configure openstack via these environment
variables (environment variable name, configuration option)
- OS_KEYNAME openstack_keyname
- OS_NETWORK openstack_network
- OS_REGION  openstack_region

### CODE REVIEW

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
Failure unrelated to patch.

**Comment by maage** [comment]
Thanks

**Pull request merged**
