### PR TITLE
(BKR-745) added el support for s390x dev installs

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
believe the failure is due to gem issues on the Jenkins. Should be re-kicked when those are resolved to confirm.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
job was aborted due to maintenance window. Will re-kick after lunch

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@tvpartytonight it's green!

**Comment by johnduarte** [comment]
:+1:  confirmed that this works to deploy puppet-agent to redhat-6 on s390x.
@kevpl you have made me VERY HAPPY!!!

**Pull request merged**
