### PR TITLE
(BKR-1500) Remove beaker-puppet and hypervisor dependencies

### PR DESCRIPTION
**Pull request by Dakta**
This is a fairly large and sprawling commit that covers the final removal of beaker-puppet dependency (including cleanup of other DSL extensions) and the hypervisor libraries. Also removed is beaker-hiera.

Probably best reviewed commit-by-commit. See puppetlabs/beaker-puppet#55 and

### CODE REVIEW

**Comment by Dakta** [comment]
Blocked by #1537

**Comment by Dakta** [comment]
Jenkins, retest this please.

**Comment by Dakta** [comment]
Jenkins, retest this please.

**Comment by Dakta** [comment]
Jenkins, retest this please.

**Comment by Dakta** [comment]
Jenkins, retest this please.

**Comment by Dakta** [comment]
Jenkins, retest this please.

**Comment by kevpl** [comment]
Jenkins, retest this please

**Comment by kevpl** [comment]
Jenkins, retest this please

**Pull request merged**
