### PR TITLE
(BKR-155) Add simple tagging to vmpooler hosts

### PR DESCRIPTION
**Pull request by sschneid**
Manually testing this against vmpooler-dev (internal) I end up with a VM tagged as such:

```
{
  "ok": true,
  "d6nz94h38x79lrn": {
    "template": "debian-7-x86_64",
    "lifetime": 2,
    "running": 0.0,
    "tags": {
      "jenkins_build_url": "",
      "department": "unknown",
      "project": "Beaker",
      "created_by": "sschneider"
    },
    "domain": "delivery.puppetlabs.net"
  }
}
```

### CODE REVIEW

**Comment by anodelman** [comment]
Broke spec:
```
1) Beaker::Vmpooler#provision provisions hosts from the pool
     Failure/Error: vmpooler.provision
     NameError:
       uninitialized constant MockNet::HTTP::Put
     # ./lib/beaker/hypervisor/vmpooler.rb:130:in `block in provision'
     # ./lib/beaker/hypervisor/vmpooler.rb:120:in `each'
     # ./lib/beaker/hypervisor/vmpooler.rb:120:in `each_with_index'
     # ./lib/beaker/hypervisor/vmpooler.rb:120:in `provision'
     # ./spec/beaker/hypervisor/vmpooler_spec.rb:51:in `block (3 levels) in <module:Beaker>'

  2) Beaker::Vmpooler#cleanup cleans up hosts in the pool
     Failure/Error: vmpooler.provision
     NameError:
       uninitialized constant MockNet::HTTP::Put
     # ./lib/beaker/hypervisor/vmpooler.rb:130:in `block in provision'
     # ./lib/beaker/hypervisor/vmpooler.rb:120:in `each'
     # ./lib/beaker/hypervisor/vmpooler.rb:120:in `each_with_index'
     # ./lib/beaker/hypervisor/vmpooler.rb:120:in `provision'
     # ./spec/beaker/hypervisor/vmpooler_spec.rb:70:in `block (3 levels) in <module:Beaker>'
```

**Comment by sschneid** [comment]
@anodelman on it.

**Comment by sschneid** [comment]
@puppetlabs-jenkins retest this please!

**Comment by sschneid** [comment]
@puppetlabs-jenkins darn you!

**Comment by sschneid** [comment]
@puppetlabs-jenkins retest this please.

**Pull request closed without merging**
