### PR TITLE
(BKR-685) Support openstack user_data

### PR DESCRIPTION
**Pull request by azhurbilo**

### CODE REVIEW

**Comment by azhurbilo** [comment]
this PR based on CLOSED PR https://github.com/puppetlabs/beaker/pull/1050
@kevpl could you review this PR?

**Comment by kevpl** [comment]
Thanks for this submission @azhurbilo! Would you please add a section in the [Openstack hypervisor doc](https://github.com/puppetlabs/beaker/blob/master/docs/hypervisors/openstack.md) explaining how people use your new change? We're working on improving our docs, and one of the things we'd like to start doing is have new changes come through with explanations for how to use them. Thanks!

**Comment by azhurbilo** [comment]
@kevpl , done. Doc was updated.

**Comment by kevpl** [comment]
@azhurbilo thanks for adding the doc!

Would you mind moving that information to its own section of the doc, like how the [vagrant hypervisor doc](https://github.com/puppetlabs/beaker/blob/master/docs/hypervisors/vagrant.md) is structured? The reason for this is that section is titled "Basic Openstack hosts file", so I'd rather not confuse people by having it contain all of the custom options that can be supplied. You can see what a change like this would look like in #1133.

**Comment by azhurbilo** [comment]
@kevpl , done. Could you review?

**Comment by kevpl** [comment]
looks good @azhurbilo, thanks for the great info in the docs! 💯 

kicking off automated tests now

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Pull request merged**
