### PR TITLE
(GH-632) Fix Network creation

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by anodelman** [comment]
Last comment still current.

**Comment by mcanevet** [comment]
@anodelman fixed

**Comment by kevpl** [comment]
@mcanevet, sorry for the miscommunication, but we mean putting the github issue in the commit message itself, not the PR title.  Let us know if you have any questions about this.

**Comment by mcanevet** [comment]
@kevpl fixed

**Comment by kevpl** [comment]
@mcanevet thanks.  I'll kick off testing now

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
