### PR TITLE
(BKR-321) lxc hypervisor driver

### PR DESCRIPTION
**Pull request by qvicksilver**
Slightly modified version of Ashish:s PR with yard docs and rspec tests

### CODE REVIEW

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
We do not currently have an lxc maintainer - are you willing to take that on should this PR land?  You'd need to be available to do reviews and provide lxc advice.

**Comment by qvicksilver** [comment]
@anodelman I'm willing to provide whatever support I can give as maintainer for the lxc code but I'm pretty fresh wh

**Comment by qvicksilver** [comment]
Did indeed forget to rebase, this one is rebased on to current master

**Comment by kevpl** [comment]
@qvicksilver, unfortunately, our Jenkins is internal at this point, so you won't be able to see the results.

It looks like you have some commits polluting your change history.  We don't usually merge PRs that have merge commits in them.  Also, you have some other changes that don't appear to be needed for the lxc hypervisor in them, but I'm assuming those are related to the merge commits.

Once you clean this up, I look forward to getting it into Beaker!

Thanks,
KI

**Comment by qvicksilver** [comment]
Made a clean branch and created a PR from it in https://github.com/puppetlabs/beaker/pull/985

**Pull request closed without merging**
