### PR TITLE
remove sshd_config injection in an f5 platform

### PR DESCRIPTION
**Pull request by lmayorga1980**

### CODE REVIEW

**Comment by mchllweeks** [comment]
Jenkins test this please.

**Comment by hunner** [comment]
Originally this step was part of the hypervisor's host preparation steps. The F5 module included a hypervisor in-source but was migrated out to beaker's AWS hypervisor, which was then moved out to the beaker-aws gem. The code for correctly preparing root access on an F5 is built-in to the beaker-aws gem at https://github.com/puppetlabs/beaker-aws/blob/0.2.0/lib/beaker/hypervisor/aws_sdk.rb#L578-L591

Why did beaker start doing it again? Has this code been moved out of the hypervisors? Should the beaker-aws gem also be fixed up to account for that, or should the prep code be moved out of beaker-aws and back into beaker?

**Comment by lmayorga1980** [comment]
@hunner I am not aware of `beaker-aws` gem but I know puppetlabs uses it in their puppet modules. However, for a vagrant f5 box it was trying to configure sshd in a classic linux form. The way sshd is configured in f5 is through `tmsh`.

**Comment by lmayorga1980** [comment]
For some reason I cannot see the details of the jenkins failure.

**Comment by hunner** [comment]
@lmayorga1980 Ah vagrant, that would explain why I didn't run into this before. Even when I was developing on a vagrant f5 instance I always prepped the vm by hand in the webui (because licenses couldn't be automated afaict) and skipped beaker provisioning on it. I moved to aws for ephemeral instance testing because they had licensing built-in.

Unfortunately the jenkins is not accessible publicly. It looks like the only failure is unrelated to your change though so no worries.

**Comment by lmayorga1980** [comment]
@hunner hope this can be merged soon. :beer:

**Comment by mchllweeks** [comment]
@lmayorga1980 Can you please pre-pend your commit message with (maint) and add a test so we can be sure not to break this in the future.  Thx!

**Comment by lmayorga1980** [comment]
@mchllweeks :thinking: Where do you suggest to add the tests?

**Comment by mchllweeks** [comment]
Jenkins retest this please

**Comment by mchllweeks** [comment]
Jenkins retest this please

**Comment by mchllweeks** [comment]
Failures from the tests are unrelated to this change.  I can matrix reload the failing test and it passes.

**Pull request merged**
