### PR TITLE
(BKR-542) remove hosts object from log about execution against empty …

### PR DESCRIPTION
**Pull request by pondohva**
…host list

### CODE REVIEW

**Comment by kevpl** [comment]
@pondohva, thanks for submitting this patch!

while I agree that printing `block_hosts` in the empty array case doesn't look useful, I like having the hosts array printed to get a reminder of what was cut.  Why cut `hosts` as well?

**Comment by pondohva** [comment]
@kevpl I was too lazy to do that. Ok, I'll look into hosts dump

**Comment by kevpl** [comment]
@pondohva I was actually referring to not cutting as much, no additional work needed.  So that string would become something like:

    against an empty array of hosts (filtered from #{hosts})

**Comment by anodelman** [comment]
I think that we can keep the hosts dump, but change the message to an info?

**Comment by pondohva** [comment]
Well, finally fix it, sorry for delay. BTW, I commented to jira with loooong logger string

**Comment by kevpl** [comment]
@pondohva ok, you definitely get different output than we do.  Rather than creating the array implicitly, you could make it explicit with something like this:

    hosts.map { |h| h.name }

If you do decide to continue fixing this, please make sure to add a spec test as well.

Thanks,
Kevin

**Comment by pondohva** [comment]
@kevpl sure, I'll try to fix this as soon as I can. Could you merge this PR with severity decreasing, please? I'd like to see it in next beaker release :)

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Pull request merged**
