### PR TITLE
(BKR-76) created first pre-suite acceptance tests

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
failures don't appear related, but transient.  Re-running tests

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by anodelman** [comment]
Just going to wait here on having the backend smoketest set up to exercise this code.

**Comment by kevpl** [comment]
failures unrelated, but this is waiting on BKR-207 work.

**Pull request merged**
