### PR TITLE
(PE-17093) Fix noask directory path

### PR DESCRIPTION
**Pull request by demophoon**
Prior to this commit I attempted to use a variable that doesn't exist
`noask_directory`.
This commit uses the `opts[:copy_dir_external]` varible instead, which
should be provided by beaker, and default to `/root`

Added typo fix to @highb's PR here since I don't have write permissions to his fork.

### CODE REVIEW

**Comment by jpartlow** [comment]
@demophoon's going to do a manual sparc install with this patch to test.

**Comment by demophoon** [comment]
Frankenbuilder fun passes locally with our sparc 10 box:
```sh
              - Test Case Summary for suite 'pre_suite' -
       Total Suite Time: 651.04 seconds
      Average Test Time: 651.04 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

Beaker completed successfully, thanks.
# Frankenbuilder Settings
# ----------------------------------------
# HYPERVISOR           | vmpooler
# CONFIGURATION        | mono
# BUILD                | 2016.2.1
# PLATFORM             | el-7-x86_64
# TEMPLATE             | centos-7-x86_64
# PRE_SUITE_TESTS[@]   | /Users/britt/projects/work/yellow/pe_acceptance_tests/setup/install.rb
# HELPER               | /Users/britt/projects/work/yellow/pe_acceptance_tests/lib/beaker_helper.rb
# AGENTS[@]            | solaris-10-sparc
# PRESERVE_HOSTS       | always
# ----------------------------------------
# Rerun with: ./builder 2016.2.1 --agent solaris-10-sparc --vmpooler --install --pe_acceptance_tests pe_acceptance_tests
```

I am a little bit confused at the error with jenkins however, I cannot get my local specs to fail at all. @kevpl Maybe you can shed some light on why that windows box is failing in jenkins

**Comment by kevpl** [comment]
yep, looks like you're facing the same issue we are in master: [RE-8035](https://tickets.puppetlabs.com/browse/RE-8035) (internal link). We'll keep you updated as we go through that process.

**Comment by jpartlow** [comment]
@kevpl @demophoon from this morning's stand up, it sounded like the pr failure was not a blocker, and that you had tested this separately, Britt, and this could be merged?

**Comment by demophoon** [comment]
Yes, this is ready to be merged as far as I'm concerned.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
I'd like to have this run through our CI once now that we've disabled that cell that was failing in an unrelated way

**Comment by demophoon** [comment]
Sounds good to me

**Pull request merged**
