### PR TITLE
(BKR-1060) make `beaker init` not require a `--hypervisor argument`

### PR DESCRIPTION
**Pull request by mchllweeks**

### CODE REVIEW

**Comment by mchllweeks** [comment]
retest this please

**Comment by ferglor** [comment]
So it turns out, the changes I was going to suggest you make, I have as part of PR for the provision subcommand, so I can just rebase my changes on top of yours once this goes in

Other than that, the only suggestion I would have is to follow the commit message conventions, i.e. currently, your commit message is as follows:

{code}BKR-1060: [beaker subcommands] make `beaker init` not require a `--hypervisor` argument{code}

But ideally it would look something like:

{code}(BKR-1060) make `beaker init` not require a `--hypervisor` argument{code}

So really it's just wrapping the ticket number in parentheses, and there's no need to specify the "beaker subcommands" epic

Hopefully that doesn't come across as too pedantic! But it's 👍 from me once we get the acceptance tests passing again!

**Comment by mchllweeks** [comment]
Thx @ferglor!  Appreciate the feedback on commit messages. 👍

**Comment by mchllweeks** [comment]
retest this please

**Pull request merged**
