### PR TITLE
(BKR-695) fix configure_puppet_on for windows

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
I've created a new job that is a copy of the old job with the windows platform added back into the matrix (internal link) [here](https://jenkins-beaker.delivery.puppetlabs.net/job/qe_beaker_intn-sys_beaker-rspec-integration-bkr695/).  It's passing, so the module issue has been tested.  Once this is merged, I'll put that entry back into the old job, and delete the copied job.

**Comment by justinstoller** [comment]
This approach is one of the approaches suggested by @Iristyle, simplifies the code, and is consistent with other ways we do this in Beaker. The job Kevin built is passing appropriately. :+1:

**Comment by waynr** [comment]
:+1: looks good to me

**Pull request merged**
