### PR TITLE
(MAINT) Use JSON.pretty_generate to create JSON output

### PR DESCRIPTION
**Pull request by kurtwall**
`JSON.dump` ruins the formatting of JSON files, which can make TK config files difficult to read. This commit replaces `JSON.dump` with `JSON.pretty_generate` to preserve config file formatting and readability.

### CODE REVIEW

**Comment by kurtwall** [comment]
@erikPrime might enjoy this.

**Comment by kurtwall** [comment]
Assigning to @tvpartytonight for starters

**Comment by erikPrime** [comment]
:100:

**Comment by nwolfe** [comment]
@kurtwall Need to update the expected `:dump` call in the spec test too:
```
  1) ClassMixedWithDSLHelpers modify_tk_config given a non-empty options hash given a true value to its `replace` parameter dumps to the SUT config file path
     Failure/Error: expect( JSON ).to receive(:dump)
```

**Comment by kevpl** [comment]
@kurtwall there's another ref to `:dump` on line 75 that's failing now.

You can run the specs locally for this file with 

    bundle exec rspec spec/beaker/dsl/helpers/tk_helpers_spec.rb

to make sure there aren't any other failures here, and just leave off the filename to be sure there aren't any spec failures in general.

**Comment by kurtwall** [comment]
No more spec failures. 
```
$ be rspec spec/beaker/dsl/helpers
Finished in 1.73 seconds (files took 0.76908 seconds to load)
136 examples, 0 failures
```
Do you want the commits squashed?

**Comment by nwolfe** [comment]
> Do you want the commits squashed?

GitHub added the ability to squash commits when you click the `Merge pull request` button, so we can do this from our end!

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kurtwall** [comment]
@puppetlabs-jenkins retest this please

**Comment by kurtwall** [comment]
Any idea when this might be merged and released?

**Comment by tvpartytonight** [comment]
@kurtwall thanks for the PR! I will merge it now, and it will be in the next beaker release, schedule for this Wednesday, August 10th. 

You can always check for the date of the next release in the [beaker wiki](https://github.com/puppetlabs/beaker/wiki).

**Comment by kurtwall** [comment]
@tvpartytonight W00T!

**Pull request merged**
