### PR TITLE
(BKR-1534) permit user environment on osx-10.14

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by mihaibuzgau** [comment]
👍

**Comment by mattkirby** [comment]
retest this please

**Comment by kevpl** [comment]
re-kicking since last test results were purged over the holiday break.

retest this please

**Comment by gimmyxd** [comment]
retest this please

**Comment by gimmyxd** [comment]
retest this please

**Comment by mihaibuzgau** [comment]
looks like the tests have passed. @mattkirby, @speedofdark are you OK if we merge this?

**Pull request merged**
