### PR TITLE
(BKR-317) More usable configure_foss_defaults_on

### PR DESCRIPTION
**Pull request by anodelman**
- create configure_defaults_on that provided a type sets the correct
  defaults per-host, will also remove any existing defaults

### CODE REVIEW

**Comment by MikaelSmith** [comment]
`install_puppet_on` doesn't configure the type, so I think you can end up in a state where things are broken. If you do `install_puppet_on host, 4.0.0` while `type` is set to `'foss'`, it will install `puppet-agent`, then configure paths for `foss` (old paths). This is what would happen if you had `puppet-agent` installed and configured, then uninstalled it and only did `install_puppet_on`.

**Comment by anodelman** [comment]
install_puppet_on calls a bunch of sub methods (like install_puppet_from_rpm) which in turn call configure_foss_defaults_on - so the type should be correctly set post installation.

**Comment by MikaelSmith** [comment]
[`configure_foss_defaults_on`](https://github.com/puppetlabs/beaker/blob/master/lib/beaker/dsl/install_utils/foss_utils.rb#L41) changes behavior based on `type`, but doesn't update it. I don't see anywhere in the call chains for `install_puppet_on` that it would update the node's `type`.

**Comment by MikaelSmith** [comment]
Other than that, appears to work for my use case.

**Comment by anodelman** [comment]
It's a little deep in the chain, but  add_platform_foss_defaults will be called and will set type='foss' (unless the host is already identified as 'aio' and then it will leave it alone).

**Comment by anodelman** [comment]
Failures unrelated to patch.

**Comment by MikaelSmith** [comment]
That is the workflow though...
- upgrade to puppet-agent
- `configure_defaults_on host, 'aio'`, which will call `add_aio_defaults_on` and set `type='aio'`
- uninstall puppet-agent
- `install_puppet_on`, which will install (foss) puppet while type is 'aio'.

I think that's an API problem, but if it can't be fixed then I can do `configure_defaults_on host, 'foss'` before repeating `install_puppet_on`.

**Comment by anodelman** [comment]
It sounds like you need something as part of the "uninstall puppet-agent" step that could remove all current defaults?  Then the install_puppet_on would run clean and assume 'foss' type?

**Comment by MikaelSmith** [comment]
Yeah, that would work.

**Comment by anodelman** [comment]
I'll update this patch to cover that workflow.

**Comment by MikaelSmith** [comment]
If I use `configure_defaults_on host, 'foss'` after the "uninstall puppet-agent" step, everything works. So I'm ok with this API.

I still wonder about being able to do `install_puppet_on` and end up with the wrong configuration - i.e. configure a node with `type='aio'` then do `install_puppet_on host`. You'll end up with puppet 3.8 installed but paths setup for aio. I suppose that's the beaker users problem.

**Comment by anodelman** [comment]
Failure unrelated to patch.

**Pull request merged**
