### PR TITLE
MAINT - Improve F5 enable root

### PR DESCRIPTION
**Pull request by LuvCurves**
Set password before storing it in the host ssh password value, instead of the host ssh value

### CODE REVIEW

**Comment by kevpl** [comment]
@LuvCurves, would you please prefix the commit messages with a ticket or `(MAINT)`?  I think maint would work here, otherwise I would expect testing to accompany this change.

**Comment by LuvCurves** [comment]
@kevpl Done.  Sorry, didn't see this until now.  This has indeed been tested. ;)

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@LuvCurves sorry, I meant the git commit messages themselves.  You can do this with `git rebase -i`.

**Comment by anodelman** [comment]
Please update your commit messages on this and we should be good to go.

**Comment by anodelman** [comment]
Still waiting on commit message update.

**Comment by LuvCurves** [comment]
Done.

**Comment by anodelman** [comment]
@LuvCurves Could you file a jira ticket to associate this commit with?  We are moving away from (maint) so that we can provide accurate release notes.

**Comment by kevpl** [comment]
last comment still current

**Comment by anodelman** [comment]
Closing out due to inactivity.

**Pull request closed without merging**
