### PR TITLE
BKR-1089: Cleanup array quoting

### PR DESCRIPTION
**Pull request by cdenneen**
* Previous PR caused quoting issue which made this not work properly
  on Windows with arrays.
  Fixed the quoting in order to rectify this issue and updated tests.

### CODE REVIEW

**Comment by rishijavia** [comment]
@puppetlabs-jenkins test this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
timed out, re-kicking

@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@cdenneen in the future, if you put parens around the ticket reference rather than a colon after, we won't squash it when merging. Thanks for the improvement!

**Comment by cdenneen** [comment]
@kevpl Where was the squash?

**Pull request merged**
