### PR TITLE
(BKR-696) Fix corruption of `opts[:ignore]` when using `rsync`

### PR DESCRIPTION
**Pull request by joshuaspence**

### CODE REVIEW

**Comment by mchllweeks** [comment]
@jenkins test this please

**Comment by mchllweeks** [comment]
retest this please

**Comment by mchllweeks** [comment]
@joshuaspence We have updated our contributing standards: [CONTRIBUTING.md](CONTRIBUTING.md).

Please add an entry in the [CHANGELOG.md](CHANGELOG.md) as another commit and I will merge this PR for our next release.

**Comment by mchllweeks** [comment]
last comment current

**Comment by joshuaspence** [comment]
Done. Changelog has been updated.

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Pull request merged**
