### PR TITLE
(BKR-240) added a reason code on reboot for windows

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
@anodelman I don't think support from the OS is the issue here.  According to (their docs)[https://technet.microsoft.com/en-us/library/cc732503.aspx?f=255&MSPPError=-2147217396], it's supported in both win2003r2 & win2008r2.

Checking into the Jenkins failure, it's only the echo command that's failing after, the execution of the shutdown command doesn't appear to have a problem.  I can run the command locally, and get the result that an echo issued right after a reboot will succeed, but if I preserve the host and try to ssh into it after, I can't get to it (a vmpooler host) for another minute or two.  I get the same type of failure seen in the Jenkins if I sleep during the test before running the echo command.  I suspect that this is a timing issue with the reboot, and think the solution here is a long back off to let the reboot finish, or to block the return until the ssh connection successfully dies and restarts after reboot finishes.

**Comment by anodelman** [comment]
I think that the solution to windows reboot is in:

https://github.com/puppetlabs/beaker/pull/802

I discovered the issue when I was playing around with is_cygwin and fixed it so that I could get my local testing running.

**Comment by kevpl** [comment]
#802 just merged, so I'll kick off another cycle of testing here to see if that solves this issue.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by anodelman** [comment]
retest this please

**Comment by kevpl** [comment]
failure unrelated

**Pull request merged**
