### PR TITLE
[QENG-3063] [DO NOT MERGE] Introduce absurd logging for debugging purposes

### PR DESCRIPTION
**Pull request by rick**
Attempting to diagnose a weird in-jenkins-only test failure where on debian7 and centos7 sometimes hosts will not reboot. Not only this, but no output is received once the reboot sequence is started; so jenkins times out after 10 minutes of lack of output.

Here attempting to both flush logging destinations on all output for this test, as well as introducing a large amount of additional output.  Let's see if we can get more information on this test failure.

/cc @puppetlabs/beaker

### CODE REVIEW

**Comment by rick** [comment]
Will run more builds like this -- it looks to me like the `flush()` calls are probably sufficient (which is fortunate, as generating lots of output all the time would be unsatisfactory).

Note that there are a couple of failures on this branch, which all appear to be coming from yet another transient failure related to rsync creation of remote files on debian7/centos7 (systemd :hankey:?):


http://jenkins-beaker.delivery.puppetlabs.net/job/qe_beaker_intn-sys_beaker-acceptance-base-vpool/1085/agent=debian7/consoleFull
```
dsl::helpers::host_helpers #create_remote_file
  Warning: No suitable hosts with: {:platform=>/^centos|el-\d|fedora/}
  
  No suitable hosts found
  
  * #create_remote_file CURRENTLY does not fail and does not create a remote file when the remote path does not exist, using rsync
    rsync: localhost:/tmp/beaker20151102-24227-u7fkkz to root@10.32.115.55:/non/existent/testfile.txt {:ignore => }
    rsync returned #<Rsync::Result:0x00000004524078 @raw="Warning: Permanently added '10.32.115.55' (ECDSA) to the list of known hosts.\r\nrsync: change_dir#3 \"/non/existent\" failed: No such file or directory (2)\nrsync error: errors selecting input/output files, dirs (code 3) at main.c(643) [Receiver=3.0.9]\nrsync: connection unexpectedly closed (9 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]\n", @exitcode=12>
```

Will need to file a ticket for that one as well.

**Comment by rick** [comment]
More detailed build log for that rsync failure:

```
  * #create_remote_file creates a remote file with the specified contents, using rsync
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) 16:59:46$ getent passwd root
      root:x:0:0:root:/root:/bin/bash
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) executed in 0.01 seconds
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) 16:59:46$ mktemp -dt .XXXXXX
      /tmp/.2gDapN
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) executed in 0.01 seconds
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) 16:59:46$ chown root:root /tmp/.2gDapN
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) executed in 0.01 seconds
    rsync: localhost:/tmp/beaker20151102-16118-16kn7mf to root@10.32.125.143:/tmp/.2gDapN/testfile.txt {:ignore => }
    rsync returned #<Rsync::Result:0x00000003420a10 @raw="ssh: connect to host 10.32.125.143 port 22: Connection timed out\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n", @exitcode=255>
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) 17:00:49$ cat /tmp/.2gDapN/testfile.txt
      cat: /tmp/.2gDapN/testfile.txt: No such file or directory
    
    dk0lgktzy4231a3.delivery.puppetlabs.net (centos7-64-1) executed in 0.01 seconds
    Exited: 1
    #<Beaker::Host::CommandFailure: Host 'dk0lgktzy4231a3.delivery.puppetlabs.net' exited with 1 running:
     cat /tmp/.2gDapN/testfile.txt
    Last 10 lines of output were:
    	cat: /tmp/.2gDapN/testfile.txt: No such file or directory>
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/host.rb:311
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/dsl/helpers/host_helpers.rb:73
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/shared/host_manager.rb:115
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/dsl/patterns.rb:35
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/dsl/helpers/host_helpers.rb:63
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:86
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/dsl/structure.rb:43
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:79
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/dsl/structure.rb:230
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:77
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/dsl/structure.rb:58
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:3
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_case.rb:128
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_case.rb:128
    /usr/local/rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/benchmark.rb:295
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_case.rb:125
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_suite.rb:311
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_suite.rb:308
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_suite.rb:308
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/test_suite.rb:357
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/cli.rb:157
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/lib/beaker/cli.rb:99
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/bin/beaker:6
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/vendor/bundle/ruby/1.9.1/bin/beaker:23
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/vendor/bundle/ruby/1.9.1/bin/beaker:23
    Warning: /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb errored in 127.02 seconds
    Begin /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/centos7/acceptance/tests/base/dsl/helpers/host_helpers/create_tmpdir_on_test.rb
```

**Comment by rick** [comment]
Aha:

```
    rsync: localhost:/tmp/beaker20151103-48010-11hekb6 to root@10.32.123.87:/tmp/.EzPdCh/testfile.txt {:ignore => }
    rsync returned #<Rsync::Result:0x00000004616148 @raw="@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nIT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!\r\nSomeone could be eavesdropping on you right now (man-in-the-middle attack)!\r\nIt is also possible that a host key has just been changed.\r\nThe fingerprint for the RSA key sent by the remote host is\n22:2b:05:7e:a1:86:f5:0e:9b:28:99:a9:ec:df:f1:64.\r\nPlease contact your system administrator.\r\nAdd correct host key in /var/lib/jenkins/.ssh/known_hosts to get rid of this message.\r\nOffending RSA key in /var/lib/jenkins/.ssh/known_hosts:65\r\n  remove with: ssh-keygen -f \"/var/lib/jenkins/.ssh/known_hosts\" -R 10.32.123.87\r\nPassword authentication is disabled to avoid man-in-the-middle attacks.\r\nKeyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.\r\n<f+++++++++ beaker20151103-48010-11hekb6\n", @exitcode=0>

```

**Comment by rick** [comment]
And on this log, we see that the hosts array version can also fail (makes sense):

http://jenkins-beaker.delivery.puppetlabs.net/job/qe_beaker_intn-sys_beaker-acceptance-base-vpool/1088/agent=debian7/console

```
  * #create_remote_file creates remote files on all remote hosts, when given an array, using rsync
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) 06:52:35$ getent passwd root
      root:x:0:0:root:/root:/bin/bash
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) executed in 0.00 seconds
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) 06:52:35$ mktemp -dt .XXXXXX
      /tmp/.pl0tvq
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) executed in 0.00 seconds
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) 06:52:35$ chown root:root /tmp/.pl0tvq
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) executed in 0.00 seconds
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) 06:52:35$ mkdir -p /tmp/.pl0tvq
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) executed in 0.00 seconds
    
    b5afzq25naqloke.delivery.puppetlabs.net (debian7-64-2) 06:52:35$ mkdir -p /tmp/.pl0tvq
    
    b5afzq25naqloke.delivery.puppetlabs.net (debian7-64-2) executed in 0.02 seconds
    rsync: localhost:/tmp/beaker20151103-45995-gztayu to root@10.32.115.77:/tmp/.pl0tvq/testfile.txt {:ignore => }
    rsync returned #<Rsync::Result:0x00000003b5adf8 @raw="<f+++++++++ beaker20151103-45995-gztayu\n", @exitcode=0>
    rsync: localhost:/tmp/beaker20151103-45995-gztayu to root@10.32.113.116:/tmp/.pl0tvq/testfile.txt {:ignore => }
    rsync returned #<Rsync::Result:0x00000003b72868 @raw="ssh: connect to host 10.32.113.116 port 22: Connection timed out\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n", @exitcode=255>
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) 06:53:38$ cat /tmp/.pl0tvq/testfile.txt
      This is a simple text file.
      
      It has three lines.
    
    w50c9xhu3f313ta.delivery.puppetlabs.net (debian7-64-1) executed in 0.01 seconds
    
    b5afzq25naqloke.delivery.puppetlabs.net (debian7-64-2) 06:53:38$ cat /tmp/.pl0tvq/testfile.txt
      cat:       /tmp/.pl0tvq/testfile.txt      : No such file or directory
    
    b5afzq25naqloke.delivery.puppetlabs.net (debian7-64-2) executed in 0.01 seconds
    Exited: 1
    #<Beaker::Host::CommandFailure: Host 'b5afzq25naqloke.delivery.puppetlabs.net' exited with 1 running:
     cat /tmp/.pl0tvq/testfile.txt
    Last 10 lines of output were:
    	cat: /tmp/.pl0tvq/testfile.txt: No such file or directory>
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/host.rb:311
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/dsl/helpers/host_helpers.rb:73
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/shared/host_manager.rb:115
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/dsl/patterns.rb:35
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/dsl/helpers/host_helpers.rb:63
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:174
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:173
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:173
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/dsl/structure.rb:43
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:165
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/dsl/structure.rb:230
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:163
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/dsl/structure.rb:58
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb:3
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_case.rb:128
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_case.rb:128
    /usr/local/rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/benchmark.rb:295
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_case.rb:125
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_suite.rb:311
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_suite.rb:308
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_suite.rb:308
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/test_suite.rb:357
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/cli.rb:157
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/lib/beaker/cli.rb:99
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/bin/beaker:6
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/vendor/bundle/ruby/1.9.1/bin/beaker:23
    /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/vendor/bundle/ruby/1.9.1/bin/beaker:23
    Warning: /var/lib/jenkins/workspace/qe_beaker_intn-sys_beaker-acceptance-base-vpool/agent/debian7/acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb errored in 64.33 seconds
```

**Comment by rick** [comment]
I think I have the rsync problem figured out, and if my theory is correct, it's related to rebooting hosts and changing IP addresses:

 - Various tests run, using SSH to operate on the SUT
 - SSH records host key information for the SUT host(s) on first connect
 - a reboot is issued at some point during the suite
 - if a host H receives a new IP address during the reboot then we will see the next connection go through a full fibonacci set of retries, and then it will connect via the vmhostname
 - when performing a `create_remote_file` via rsync, connections to the SUT happen over an SSH-mediated transport
 - if a host got a new IP then the stored host key information for that host no longer matches the host key information on the new host; a host key mismatch error is registered and the rsync operation fails (but is not recorded properly as a failure)

This may be the same problem that someone else was reporting with scp operations failing strangely in some cases.

**Comment by rick** [comment]
Going to take another pass at debugging this in a different way, to see if I can confirm / disconfirm this theory.

**Comment by rick** [comment]
Incorporated all the in-flight work from https://github.com/puppetlabs/beaker/pull/1006 so I can ignore reboot issues and focus on rsync issues.

**Comment by rick** [comment]
retest this please

**Comment by rick** [comment]
The strict host checking option syntax fix does appear to fix a category of problems, but there's still something amiss. I believe the problem now is that there can sometimes be a connection failure or timeout via rsync on nodes whose IPs changed after reboot. The simplest fix would be to clear the `host['ip']` setting in the SSH connection fallback code path once connecting via `@ip` has failed (which gets triggered on the first connection after reboot).

Bigger-picture, the rsync code paths are less robust. It's worth investigating how often these are used and whether ssh-only (scp) would suffice instead.

**Comment by electrical** [comment]
@rick with regards to the SSH key being saved I opened https://tickets.puppetlabs.com/browse/BKR-471 a while ago.
Its something I still want to look into to solve as its highly annoying.

**Comment by rick** [comment]
@electrical thanks for the pointer!  I'm going land the core reboot-related things in #1006; and then continue on here with debugging the remainder of the rsync-related things here and land them in a separate PR, and that will come in handy.

**Comment by rick** [comment]
Closing.  This technique is always available later.

**Pull request closed without merging**
