### PR TITLE
(BKR-239) Remove dependency on puppet-dashboard rake tasks...

### PR DESCRIPTION
**Pull request by anodelman**
... for shallow gravy.

- do that

### CODE REVIEW

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
Failures unrelated to patch.

**Comment by kevpl** [comment]
@anodelman don't we need to keep this to work with older versions?

**Comment by anodelman** [comment]
We do not currently have any pipelines using anything pre 3.7 (other than beaker, that does a 3.3.2 -> 3.7.2 upgrade test that is passing).  So there is a risk here, but it is low.  I think that we can clean up breakage in the future, but we need this fix right away.

**Comment by electrical** [comment]
Will this break anything for PE 3.3.x test runs? ( I'm starting to drop 3.1.x and 3.2.x )

**Comment by anodelman** [comment]
I did a successful 3.3.2 install, so there's a high chance of success.  If we just consider this too risky we could wrap the call in a version check?

**Comment by electrical** [comment]
I'm assuming its causing issues for newer PE versions?
We could do either of 2 things.
1. wrap it in a version check
2. do some testing ( acceptance testing ) to see if it breaks testing runs on PE 3.1.x

**Comment by anodelman** [comment]
Wrapped in a version check, backwards compatible.

**Pull request merged**
