### PR TITLE
(BKR-705) Rename cisco platforms

### PR DESCRIPTION
**Pull request by LuvCurves**

### CODE REVIEW

**Comment by objectverbobject** [comment]
@puppetlabs-jenkins retest this please

**Comment by LuvCurves** [comment]
The failure is "Resolv::ResolvError: no address for forge-aio01-internal.ops.puppetlabs.net", which is currently true. This address can't be resolved.

**Comment by glennmatthews** [comment]
Rework of #1066

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
