### PR TITLE
make apt-get install non-interactive

### PR DESCRIPTION
**Pull request by DarkGigaByte**
I've been waiting ages for install_puppet_agent_on to finish, until I realized that it had hung up on apt-get install because of an already existing config file which should be updated but had conflicts. It was stuck on the interactive dialog...

### CODE REVIEW

**Comment by kevpl** [comment]
Hi @DarkGigaByte & thanks for the fix! If you would please add a spec test so that we can ensure we don't break this in the future & make the commit changes listed in our [CONTRIBUTING doc](https://github.com/puppetlabs/beaker/blob/master/CONTRIBUTING.md) (mostly just prefixing your git commit with `(MAINT)`), hopefully we'll be able to get this reviewed, merged, & released quickly!

**Comment by mchllweeks** [comment]
Last comment still current.

**Comment by DarkGigaByte** [comment]
Won't have the time in the next couple weeks. Maybe someone else will do it in the meantime?

**Comment by ferglor** [comment]
Last comment still current.

**Comment by kevpl** [comment]
last comment is still current. Two things to note:

- our Contributing standards have been updated, so this change will need a CHANGELOG entry as well
- if this isn't updated in a week, we'll close it as inactive

If you don't have the time to come back to this before then, feel free to close the PR yourself for now. It's not like there's any negative consequences to you either re-opening the PR later with tests or opening a new one for this.

**Pull request closed without merging**
