### PR TITLE
(BKR-349) AwsSdk Hypervisor Specs (for review <3)

### PR DESCRIPTION
**Pull request by vindir**
Hey puppet people, this is still blocked on BKR-348 and (probably) BKR-318 & BKR-367 that were submitted yesterday.

Putting this up prematurely so you can review when it's convenient.  It's grown to a large enough project I want to make sure I halt early if you hate it.

I'll continue pushing as pieces fall in place but it is currently only missing initial tests for #create_instance, #launch_nodes_on_some_subnet, and #launch_all_nodes

### CODE REVIEW

**Comment by vindir** [comment]
Forgot I had another question.  I've removed #kill_zombie_volumes and #kill_zombies since they don't appear to be called anywhere in the code base for beaker.  Are these really orphaned methods or is it possible to actually call methods directly out of the hypervisors in your beaker code and I should revert?

**Comment by anodelman** [comment]
Yes, please revert.  We use those methods for monitoring our ec2 account for orphaned instances.

**Comment by vindir** [comment]
@anodelman Reverted.  #log_instances, #kill_zombie_volumes, and #kill_zombies are all back in place.

Would it be ok with you to merge this PR once  BKR-318 & BKR-367 are merge?

If that's cool I can rebase those two PRs in and then make the changes for the final few refactors&specs in a new PR.  I imagine I'm looking at a messy rebase with those two so I figure it will be easier to do the remaining refactors in a more isolated PR.

**Comment by anodelman** [comment]
Needs a rebase.

**Comment by vindir** [comment]
@anodelman Heyo.  This has been rebased and polished up.  If you're comfortable merging the tests we have here I'll do the refactors on the launch nodes and create_instance methods separately.

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
Just doing some local sanity checking.

**Comment by vindir** [comment]
:+1:

**Comment by anodelman** [comment]
Great work on this!

**Pull request merged**
