### PR TITLE
(RE-7420) Add the ability to run FOSS tests on sles

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
@kevpl I believe this is the full change set I need for testing FOSS sles packages. I've gotten most of the way through a CI run, though I haven't seen one complete yet. Hopefully that happens today.

**Comment by mckern** [comment]
I don't know Beaker well but these changes look :heavy_check_mark:. If none of the Beaker maintainers have concerns, I am 👍 on this.

**Comment by melissa** [comment]
Beaker tests for foss puppetserver completed successfully!!!

**Comment by melissa** [comment]
@tvpartytonight tests passed

**Comment by tvpartytonight** [comment]
awesome! Thanks for adding those spec tests.

**Comment by melissa** [comment]
Thank you!

**Pull request merged**
