### PR TITLE
(BKR-180) added ability to use Beaker machine as scp middle-man for PE

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
failures unrelated

**Comment by anodelman** [comment]
We should try this out on our jenkins pe smoketest and ensure that it works.

**Comment by kevpl** [comment]
@anodelman link to this testing is in the ticket (internal).

**Comment by anodelman** [comment]
Final nit, update the do_install and do_upgrade yard docs to indicate the new supported option.

**Comment by kevpl** [comment]
@anodelman done

**Pull request merged**
