### PR TITLE
(QENG-2096) Update dev repo for new AIO repo name

### PR DESCRIPTION
**Pull request by justinstoller**
Soon AIO builds will only be published to the repo "PC1" (not
products/devel or main as previously). This allows Beaker to install
from both new AIO repos or legacy repos.

### CODE REVIEW

**Comment by justinstoller** [comment]
Recent failure caused by connectivity issues to Github when downloading lein for a couple of cells in the PDB integration test matrix (unrelated to this patch). Everything else is green.

**Comment by kevpl** [comment]
It looks like the tests here don't test the functionality added.  @justinstoller, would you add a unit test or two to verify this behavior, so that when I make changes later and break this (hopefully by accident), it'll scream in my face about it?

**Comment by justinstoller** [comment]
@kevpl, I added three tests, two to test the conditional logic of whether or not we're using PC1 vs main in debian, and one to test the order of our link checking for EL. I reorganized the tests so that the set up code was being shared as much as possible (without stubbing and trying to accurately unstub things)

**Comment by justinstoller** [comment]
Build failed because I rebased my PR and Jenkins' Git plugin did not like that.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
