### PR TITLE
(BKR-631) Add memory option to vagrant libvirt.

### PR DESCRIPTION
**Pull request by sathlan**
This add the possibility to specify the memory for each host separately
or for every host.

### CODE REVIEW

**Comment by kevpl** [comment]
@sathlan would you please separate out your spec test into its own test, so that we can easier tell in the future if we've broken the code for this change in particular?

**Comment by sathlan** [comment]
@kevpl I have made a specific test for this with a little refactoring of the vagrantfile test.  Is that ok for you ?

**Comment by kevpl** [comment]
@sathlan yep, that should work great!

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
failures unrelated to change. :+1:

**Pull request merged**
