### PR TITLE
(BKR-226) - rsync fails because of NATted ports

### PR DESCRIPTION
**Pull request by fiddyspence**

### CODE REVIEW

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
Breaks spec:

```
Failures:

  1) Beaker::Host do_rsync_to do_rsync_to logs info and call Rsync class
     Failure/Error: expect(Rsync.host).to eq('root@host.example.org')
       
       expected: "root@host.example.org"
            got: "root@default.ip.address"
       
       (compared using ==)
     # ./spec/beaker/host_spec.rb:578:in `block (3 levels) in <module:Beaker>'
```

**Comment by fiddyspence** [comment]
I've fixed the test by making it test equality with the default ip set by the make_host method, which is actually a decent test because it sets it to a string.

**Comment by anodelman** [comment]
Breaks spec ruby 2.0+:

```
  1) Beaker::Host do_rsync_to do_rsync_to logs info and call Rsync class
     Failure/Error: expect( host ).to receive(:to_s).and_return('host.example.org')
       (host.example.org).to_s(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/beaker/host_spec.rb:575:in `block (3 levels) in <module:Beaker>'
```1

**Comment by anodelman** [comment]
Still breaking spec.

**Comment by anodelman** [comment]
Last comment still current.

**Comment by anodelman** [comment]
Will close next week due to inactivity.

**Comment by anodelman** [comment]
Looks good.

**Pull request merged**
