### PR TITLE
Return false if system unavailable in web_helpers

### PR DESCRIPTION
**Pull request by trevor-vaughan**

### CODE REVIEW

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
hmmm, interesting. The CI job should have been updated when I asked it to re-test this morning, but it seems to have hit the same failure as before. Let's try again as we've seen other PRs get past this & it seems pretty clearly unrelated to your changes.

@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
my apologies @trevor-vaughan, but it looks like we're still seeing the same issue. The test should be passing as CI tests against PRs with merge commits, but it doesn't look like the git foo is working for this PR, as we still seeing this old output that is fixed by #1615:

```
14:59:11 Begin acceptance/pre_suite/subcommands/05_install_ruby.rb
14:59:11 
14:59:11 Install and configure Ruby 2.3.1 (from default) on the SUT
```

To help us get around this odd failure, would you mind doing one of these two actions:
- rebasing your changes on master & force pushing your branch
- resubmitting your changes as a new branch & PR

Normally I would say that the test results are unrelated to the change & move forward regardless, but unfortunately this failure is early enough that it's blocking a whole phase of testing that I'd at least like to see executed before we move forward with this.

If you don't have time for this soon, let me know & I can resubmit the changes as a new PR.

**Comment by trevor-vaughan** [comment]
@kevpl Rebased and pushed, no problem.

**Comment by GabrielNagy** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
our infrastructure is going through a particularly bad set of issues right now, making these tests a real dice throw. My apologies on the delay here because of this.

I'm going to try a few more times to get a good run, but I'm OK opening the success criteria so we don't delay merging this much longer unless we see something that makes us particularly suspicious. My apologies again on the delay.

@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
woot! We're passed the stage of testing that I was mostly worried about and the later failures seem unrelated to these changes, so I'm down to move forward with this!

I'm going to wait on releasing this, hoping we can get the other beaker PRs merged as well, but I'll release this tomorrow if it looks like those aren't going to get in in time.

**Pull request merged**
