### PR TITLE
(DO NOT MERGE) Winrm / winrm-fs support

### PR DESCRIPTION
**Pull request by Iristyle**
Reviving a really old PR for @DLuCJ to start digging in on.

Good luck!

### CODE REVIEW

**Comment by Iristyle** [comment]
Heads up @kevpl / @tvpartytonight - this winrm-fs support works, but may not be organized quite how you would expect (and tests may need to be rethought).  I've also talked with @DLuCJ about a few things related to this:

* The bad perf of file copies under Winrm (12x slower than SCP)
  * Related, using `ruby-prof` to find hotspots in the gem that we might want to fix upstream
* Alternative to Winrm file copies (maybe Beaker automatically creates a Windows file share and we optionally use SMB instead to copy things) - this is likely out of scope
* Using the built-in support for msiexec to install the agent over HTTP instead of copying to coordinator then out to agents (which would be a separate ticket)

The third one might be where @DLuCJ looks first to make some improvements in the overall process of Beaker installing agents on WIndows, as it could be little code change and a really good return on investment.

**Comment by kevpl** [comment]
I'm 👍 to this change. I like the way that it's organized, splitting the connection out at the host level.

If you guys want to play around with improving this before it comes into use, I'm down with that. But if that's not going to happen within a month, I think we should close this PR for not having any motion, and if reminders or something else is needed, we find a way to get those done elsewhere.

**Comment by Iristyle** [comment]
@kevpl it's my understanding that @DLuCJ is currently working on this...

**Comment by kevpl** [comment]
🆒 🆒 @Iristyle, thanks for letting me know. We'll wait a few more weeks then before coming back to this.

**Comment by DLuCJ** [comment]
@Iristyle @kevpl Yup, looking to put up some initial PRs for msiexec / winrm-fs this week.  Sorry for the delay.

**Comment by Iristyle** [comment]
I've been using a variation of the following Ruby script to profile the WinRM transfers:

```ruby
require 'winrm-fs'
require 'ruby-prof'

hostname = ENV['WIN_TEST_HOST']
opts = {
  endpoint: "http://#{hostname}:5985/wsman",
  user: 'Administrator',
  password: 'password',
  disable_sppi: true
}
conn = WinRM::Connection.new(opts)
conn.shell(:powershell) do |shell|
  output = shell.run('$PSVersionTable') do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
  puts "The script exited with exit code #{output.exitcode}"
end

file_manager = WinRM::FS::FileManager.new(conn)

RubyProf.start
file_manager.upload('/Users/Iristyle/Downloads/some_file.pdf', 'C:/')

result = RubyProf.stop

printer = RubyProf::MultiPrinter.new(result)
printer.print(:path => './rubyprof')
````

**Comment by kevpl** [comment]
@DLuCJ any news on this? No rush, I'd just like to know if this is something that's coming soon, or if maybe this should go on the backburner for now?

**Comment by DLuCJ** [comment]
@kevpl I just put up PRs in beaker/beaker-pe for agent installation over HTTP.  They need some cleaning up, but worked as of three weeks ago.   

Generally, I think this should go on the backburner. 
I have some ideas for the first point, but don't think I will manage to get around to it soon.

**Pull request closed without merging**
