### PR TITLE
(BKR-827) Vagrant port forwarding

### PR DESCRIPTION
**Pull request by bstopp**
Without this patch there is no way to forward ports from the host to guest or SUT.

With this patch ports can be forwarded using the following configuration:

```
    HOSTS:
      ubuntu-1404-x64-master:
        roles:
          - master
          - agent
          - dashboard
          - database
        platform: ubuntu-1404-x86_64
        hypervisor: vagrant
        box: puppetlabs/ubuntu-14.04-64-nocm
        box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm

        ip: 192.168.20.20
      ubuntu-1404-x64-agent:
        roles:
          - agent
        platform: ubuntu-1404-x86_64
        hypervisor: vagrant
        box: puppetlabs/ubuntu-14.04-64-nocm
        box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
        ip: 192.168.21.21
        forwarded_ports:
          apache:
            from: 10080
            to: 80
          tomcat:
            from: 8080
            to: 8080
            from_ip: '127.0.0.1'
            to_ip: '0.0.0.0'

```
In the above beaker will forward port 10080 and 8080 on the Host to port 80 and 8080 (respectively) on the Agent guest.

All options specified on the [Vagrant documentation](https://www.vagrantup.com/docs/networking/forwarded_ports.html) are supported.

This relates to the new feature ticket opened on puppetlab here:
https://tickets.puppetlabs.com/browse/BKR-827

### CODE REVIEW

**Comment by kevpl** [comment]
@bstopp thanks for the submission! Please prepend your commits with the beaker ticket just as you have the PR title, and we'll be able to take a look at this. Thanks again for submitting this, and hopefully we'll get it merged & released for you soon.

**Comment by bstopp** [comment]
Should be good now.

**Comment by kevpl** [comment]
Thanks @bstopp! Looking at the code, I'm 👍 on this change.

One last thing before we run this through the pipeline: I like your description of the change in the PR's first comment.  Would you mind putting a section describing this change just like you did there in our [Vagrant doc](https://github.com/puppetlabs/beaker/blob/master/docs/hypervisors/vagrant.md#vagrant-specific-hosts-file-settings), so that other's can more easily learn about it?

**Comment by bstopp** [comment]
Documentation updated @kevpl

**Comment by kevpl** [comment]
thanks @bstopp! Same old nit: would you prepend your commit message with the ticket reference?  Also, we don't usually merge PRs that have their own merge commits in them. Would you mind cleaning up the history for this? Sorry for all the minutia changes :-/

**Comment by bstopp** [comment]
Working on fixing that. But question: how do i validate my changes don't break other stuff w/o merging in everything from master mid-pr updates? This more of a curiosity question

**Comment by bstopp** [comment]
@kevpl I've updated the commit message but i cannot remove that merge; my documentation copy was not up-to-date when i created the branch and need the merge to bring in your updates; otherwise i'll have a conflict. I can close this PR and open a new one with a clean history if you want; just let me know.

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Comment by kevpl** [comment]
@bstopp at this point, it's fine, I can use squash & merge to get rid of the merge commit. Since I've kicked off testing, it would be best to just let it finish rather than changing the history mid-run.

For future reference, you can rebase your changes off the latest work in order to replay your commits on top of mainline changes.

**Pull request merged**
