### PR TITLE
(QENG-1970) Guard against merging custom answers on Windows

### PR DESCRIPTION
**Pull request by demophoon**
Before this commit Beaker would attempt to merge custom answers on
platforms where answers are not used. This commit guards against merging
custom answers unless there are already answers specified.

### CODE REVIEW

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
(sorry for all the test request spam, we're having instability in our internal systems)

**Comment by anodelman** [comment]
retest this please

**Comment by demophoon** [comment]
No worries :)
Thanks for looking over this PR @anodelman

**Comment by anodelman** [comment]
And now there's a rubygems outage.  Sad trombone.

**Comment by anodelman** [comment]
retest this please

**Comment by kevpl** [comment]
known failures only.  merging.

**Pull request merged**
