### PR TITLE
(QENG-780) request sets of VMs instead of one VM at a time

### PR DESCRIPTION
**Pull request by sschneid**
This PR facilitates use of vmpooler's batch-request POST API
(https://github.com/puppetlabs/vmpooler#post-vm) within beaker.

### CODE REVIEW

**Comment by sschneid** [comment]
@puppetlabs-jenkins retest this please

**Comment by sschneid** [comment]
Well that last commit apparently wasn't the right fix... @kevpl @anodelman halp!

**Comment by kevpl** [comment]
@sschneid, I took a look at this locally, and adding a mock `body=` virtual attribute to `spec/mocks.rb` solves this problem for me and gets your tests passing (inside `MockNet::HTTP::Post`):

    def body= *args
      hash
    end

**Comment by sschneid** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@sschneid sorry to nit, but would you put a tag on the Post method commit, so we can track it better?

**Pull request merged**
