### PR TITLE
(MAINT) Add README Information for Beaker Libraries

### PR DESCRIPTION
**Pull request by cowofevil**
Update the Beaker docs README to point to the public Beaker libraries.

### CODE REVIEW

**Comment by kevpl** [comment]
Looks good @cowofevil! Would you please add a `(MAINT)` prefix to your commit message, & also add a link to this doc from the main doc page?

**Comment by cowofevil** [comment]
@kevpl Updated.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by objectverbobject** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
