### PR TITLE
(BKR-6) added privatebindir for windows' old PE and FOSS types

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by joshcooper** [comment]
:+1:

**Comment by joshcooper** [comment]
For git acceptance, I see the correct `/usr/bin` prepended to PATH:

```
$ be rake ci:test:git SHA=4dae4b348ab6942d07c178fd160726e2c7895eaa CONFIG=config/nodes/win2012r2-rubyx64.yaml
...
che2lw9pzylud0n.delivery.puppetlabs.net (agent-2012r2-x86_64-rubyx64) 10:20:21$ env PATH="/usr/bin:${PATH}" cmd /c gem source --clear-all
env: cmd: No such file or directory
```

The command fails due to BKR-7 (since `PATH` is corrupted with a semicolon), but this is expected, so :+1:  to merge.

**Comment by joshcooper** [comment]
The failures are because beaker is testing against 3.7.4, which doesn't have the fixes that were made for QENG-1592 in commit [0d9d11392](https://github.com/puppetlabs/puppet/commit/0d9d113926ddc35d160191095e24441f17072f73). You may want to backport that commit to puppet#stable and pin against that version.

**Comment by anodelman** [comment]
@joshcooper I'm working on backporting test updates now so that we can get to green.

**Comment by joshcooper** [comment]
@kevpl @anodelman should be good to retest now

**Comment by anodelman** [comment]
This won't get exercised with additional testing.  Merging as-is.

**Pull request merged**
