### PR TITLE
(BKR-312) Pass opts to install_puppetlabs_release_repo method

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by anodelman** [comment]
@justinstoller Can you have a look at this?

**Comment by justinstoller** [comment]
@anodelman   :+1:

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
Broke spec:
```
Failures:

  1) ClassMixedWithDSLInstallUtils#install_puppet on debian installs latest if given no version info
     Failure/Error: subject.install_puppet
       #<ClassMixedWithDSLInstallUtils:0x0000000506af18> received :install_puppetlabs_release_repo with unexpected arguments
         expected: (vm1)
              got: (vm1, nil, {:win_download_url=>"http://downloads.puppetlabs.com/windows", :mac_download_url=>"http://downloads.puppetlabs.com/mac"})
       Diff:
       @@ -1,2 +1,5 @@
       -[vm1]
       +[vm1,
       + nil,
       + {:win_download_url=>"http://downloads.puppetlabs.com/windows",
       +  :mac_download_url=>"http://downloads.puppetlabs.com/mac"}]
       
     # ./lib/beaker/dsl/install_utils/foss_utils.rb:425:in `install_puppet_from_deb_on'
     # ./lib/beaker/dsl/install_utils/foss_utils.rb:239:in `block in install_puppet_on'
     # ./lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # ./lib/beaker/shared/host_manager.rb:93:in `block in run_block_on'
     # ./lib/beaker/shared/host_manager.rb:92:in `map'
     # ./lib/beaker/shared/host_manager.rb:92:in `run_block_on'
     # ./lib/beaker/dsl/patterns.rb:32:in `block_on'
     # ./lib/beaker/dsl/install_utils/foss_utils.rb:231:in `install_puppet_on'
     # ./lib/beaker/dsl/install_utils/foss_utils.rb:178:in `install_puppet'
     # ./spec/beaker/dsl/install_utils/foss_utils_spec.rb:244:in `block (4 levels) in <top (required)>'
```

**Comment by anodelman** [comment]
Last comment still current.

**Comment by anodelman** [comment]
Will close next week due to inactivity.

**Pull request closed without merging**
