### PR TITLE
(BKR-702) added platform-specific tag confines

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
failures unrelated to change

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
ready for a look @puppetlabs/beaker!

/cc @joshcooper @LuvCurves

**Comment by doug-rosser** [comment]
:+1:

**Comment by waynr** [comment]
:+1:

**Pull request merged**
