### PR TITLE
(BKR-1160) Fix env var setting on Cisco Nexus

### PR DESCRIPTION
**Pull request by LuvCurves**

### CODE REVIEW

**Comment by LuvCurves** [comment]
All Puppet acceptance tests passing on Cisco Nexus:
`      Test Suite: tests @ 2017-07-13 22:01:41 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 4233.78 seconds
      Average Test Time: 12.38 seconds
              Attempted: 342
                 Passed: 291
                 Failed: 0
                Errored: 0
                Skipped: 51
                Pending: 0
                  Total: 342

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:`

**Comment by LuvCurves** [comment]
All Puppet Acceptance tests passing using this PR on the Cisco IOS XR:
Test Suite: tests @ 2017-07-13 23:29:17 +0000
Host Configuration Summary -:
Test Case Summary for suite 'tests' -
Total Suite Time: 4148.04 seconds
Average Test Time: 12.13 seconds
Attempted: 342
Passed: 290
Failed: 0
Errored: 0
Skipped: 52
Pending: 0
Total: 342

**Comment by joshcooper** [comment]
Can you test both cisco's on facter, hiera, and pxp-agent too?

**Comment by McdonaldSeanp** [comment]
Facter tests pass on Cisco IOS XR: 

```
      Test Suite: tests @ 2017-07-20 10:01:50 -0700                                                                                                                                   
                                                                                                                                                                                      
      - Host Configuration Summary -                                                                                                                                                  
                                                                                                                                                                                      
                                                                                                                                                                                      
              - Test Case Summary for suite 'tests' -                                                                                                                                 
       Total Suite Time: 158.62 seconds                                                                                                                                               
      Average Test Time: 1.67 seconds                                                                                                                                                 
              Attempted: 95                                                                                                                                                           
                 Passed: 90                                                                                                                                                           
                 Failed: 0                                                                                                                                                            
                Errored: 0                                                                                                                                                            
                Skipped: 5                                                                                                                                                            
                Pending: 0                                                                                                                                                            
                  Total: 95                                                                                                                                                           
                                                                                                                                                                                      
      - Specific Test Case Status -                                                                                                                                                   
                                                                                                                                                                                      
Failed Tests Cases:                                                                                                                                                                   
Errored Tests Cases:                                                                                                                                                                  
Skipped Tests Cases:                                                                                                                                                                  
  Test Case tests/ticket_1123_facter_with_invalid_locale.rb                                                                                                                           
  Test Case tests/custom_facts/using_win32ole_should_not_hang.rb                                                                                                                      
  Test Case tests/facts/non_root_users_without_errors.rb                                                                                                                              
  Test Case tests/facts/operatingsystem_detection_after_clear_on_ubuntu.rb                                                                                                            
  Test Case tests/facts/verify_tmpfs_file_system.rb 
```

And Cisco nexus:

```
      Test Suite: tests @ 2017-07-20 10:51:20 -0700                                                                                                                                   
                                                                                                                                                                                      
      - Host Configuration Summary -                                                                                                                                                  
                                                                                                                                                                                      
                                                                                                                                                                                      
              - Test Case Summary for suite 'tests' -                                                                                                                                 
       Total Suite Time: 182.51 seconds                                                                                                                                               
      Average Test Time: 1.92 seconds                                                                                                                                                 
              Attempted: 95                                                                                                                                                           
                 Passed: 87                                                                                                                                                           
                 Failed: 0                                                                                                                                                            
                Errored: 0                                                                                                                                                            
                Skipped: 8                                                                                                                                                            
                Pending: 0                                                                                                                                                            
                  Total: 95                                                                                                                                                           
                                                                                                                                                                                      
      - Specific Test Case Status -                                                                                                                                                   
                                                                                                                                                                                      
Failed Tests Cases:                                                                                                                                                                   
Errored Tests Cases:                                                                                                                                                                  
Skipped Tests Cases:                                                                                                                                                                  
                  Test Case tests/ticket_1123_facter_with_invalid_locale.rb                                                                                                           
                  Test Case tests/custom_facts/using_win32ole_should_not_hang.rb                                                                                                      
                  Test Case tests/facts/non_root_users_without_errors.rb                                                                                                              
                  Test Case tests/facts/operatingsystem_detection_after_clear_on_ubuntu.rb                                                                                            
                  Test Case tests/facts/verify_tmpfs_file_system.rb                                                                                                                   
                  Test Case tests/options/custom_facts_load_path.rb                                                                                                                   
                  Test Case tests/options/no_custom_facts_and_load_path.rb                                                                                                            
                  Test Case tests/options/config_file/no_custom_facts_and_load_path.rb
```

**Comment by McdonaldSeanp** [comment]
pxp-agent tests are passing for Cisco nexus:

```
      Test Suite: tests @ 2017-07-20 11:21:13 -0700                                                                                                                                   
                                                                                                                                                                                      
      - Host Configuration Summary -                                                                                                                                                  
                                                                                                                                                                                      
                                                                                                                                                                                      
              - Test Case Summary for suite 'tests' -                                                                                                                                 
       Total Suite Time: 530.22 seconds                                                                                                                                               
      Average Test Time: 18.94 seconds                                                                                                                                                
              Attempted: 28                                                                                                                                                           
                 Passed: 26                                                                                                                                                           
                 Failed: 0                                                                                                                                                            
                Errored: 0                                                                                                                                                            
                Skipped: 2                                                                                                                                                            
                Pending: 0                                                                                                                                                            
                  Total: 28                                                                                                                                                           
                                                                                                                                                                                      
      - Specific Test Case Status -                                                                                                                                                   
                                                                                                                                                                                      
Failed Tests Cases:                                                                                                                                                                   
Errored Tests Cases:                                                                                                                                                                  
Skipped Tests Cases:                                                                                                                                                                  
  Test Case tests/restart_host_run_puppet.rb                                                                                                                                          
  Test Case tests/tasks/run_ps1.rb                                                                                                                                                    
Pending Tests Cases:                                                                                                                                                                  
                                           
```

And Cisco IOS XR as well: 

```
        tests/pxp-module-puppet/negative/attempt_puppet_flag_whitelist_bypass.rb passed in 7.58 seconds                                                                               
      Test Suite: tests @ 2017-07-20 13:27:21 -0700                                                                                                                                   
                                                                                                                                                                                      
      - Host Configuration Summary -                                                                                                                                                  
                                                                                                                                                                                      
                                                                                                                                                                                      
              - Test Case Summary for suite 'tests' -                                                                                                                                 
       Total Suite Time: 513.50 seconds                                                                                                                                               
      Average Test Time: 18.34 seconds                                                                                                                                                
              Attempted: 28                                                                                                                                                           
                 Passed: 26                                                                                                                                                           
                 Failed: 0                                                                                                                                                            
                Errored: 0                                                                                                                                                            
                Skipped: 2                                                                                                                                                            
                Pending: 0                                                                                                                                                            
                  Total: 28                                                                                                                                                           
                                                                                                                                                                                      
      - Specific Test Case Status -                                                                                                                                                   
                                                                                                                                                                                      
Failed Tests Cases:                                                                                                                                                                   
Errored Tests Cases:                                                                                                                                                                  
Skipped Tests Cases:                                                                                                                                                                  
  Test Case tests/restart_host_run_puppet.rb                                                                                                                                          
  Test Case tests/tasks/run_ps1.rb                                                                                                                                                    
Pending Tests Cases:                                                                                                                                                                  
                                                  
```

**Comment by McdonaldSeanp** [comment]
Hiera tests are passing on Cisco IOS XR:

```
tests/yaml_backend/05-lookup_data_with_hash_search.rb passed in 8.12 seconds                                                                                                          
      Test Suite: tests @ 2017-07-20 13:46:54 -0700                                                                                                                                   
                                                                                                                                                                                      
      - Host Configuration Summary -                                                                                                                                                  
                                                                                                                                                                                      
                                                                                                                                                                                      
              - Test Case Summary for suite 'tests' -                                                                                                                                 
       Total Suite Time: 39.57 seconds                                                                                                                                                
      Average Test Time: 6.60 seconds                                                                                                                                                 
              Attempted: 6                                                                                                                                                            
                 Passed: 6                                                                                                                                                            
                 Failed: 0                                                                                                                                                            
                Errored: 0                                                                                                                                                            
                Skipped: 0                                                                                                                                                            
                Pending: 0                                                                                                                                                            
                  Total: 6                                                                                                                                                            
                                                                                                                                                                                      
      - Specific Test Case Status -                                                                                                                                                   
                                                                                                                                                                                      
Failed Tests Cases:                                                                                                                                                                   
Errored Tests Cases:                                                                                                                                                                  
Skipped Tests Cases:                                                                                                                                                                  
Pending Tests Cases:                                                                                                                                                                  
                                      
```

And Cisco IOS XR:

```
      Test Suite: tests @ 2017-07-20 13:53:25 -0700                                                                                                                                   
                                                                                                                                                                                      
      - Host Configuration Summary -                                                                                                                                                  
                                                                                                                                                                                      
                                                                                                                                                                                      
              - Test Case Summary for suite 'tests' -                                                                                                                                 
       Total Suite Time: 40.32 seconds                                                                                                                                                
      Average Test Time: 6.72 seconds                                                                                                                                                 
              Attempted: 6                                                                                                                                                            
                 Passed: 6                                                                                                                                                            
                 Failed: 0                                                                                                                                                            
                Errored: 0                                                                                                                                                            
                Skipped: 0                                                                                                                                                            
                Pending: 0                                                                                                                                                            
                  Total: 6                                                                                                                                                            
                                                                                                                                                                                      
      - Specific Test Case Status -                                                                                                                                                   
                                                                                                                                                                                      
Failed Tests Cases:                                                                                                                                                                   
Errored Tests Cases:                                                                                                                                                                  
Skipped Tests Cases:                                                                                                                                                                  
Pending Tests Cases:                                                                                                                                                                  
                                        
```

**Comment by McdonaldSeanp** [comment]
@joshcooper this PR has been tested as requested

**Comment by joshcooper** [comment]
Thanks @McdonaldSeanp! 🚢 

@kevpl do you want to review and merge?

**Pull request merged**
