### PR TITLE
(GH-587) SSH agent forwarding for Docker and Vagrant

### PR DESCRIPTION
**Pull request by madAndroid**
This addresses #587 

I've tried to create an issue in JIRA, but I can't seem to find the correct project (I don't appear to have visibility for `QENG`) ; any help would be much appreciated.

### CODE REVIEW

**Comment by madAndroid** [comment]
Hi @kevpl,

That's been amended now .. please let me know if that's sufficient, or if there are any further changes required? thanks :)

**Comment by kevpl** [comment]
@madAndroid , awesome, the test looks much better!  Unfortunately, I see a fifth commit that's just merging changes?  We usually just rebase when code has changed elsewhere, so that we don't add new history entries like this one.

Once this is eliminated, I'll submit the code for one last test, and as long as everything looks good there, we should be able to merge this soon!

**Comment by madAndroid** [comment]
Unfortunately it looks as though that merge commit was merged into master prior to me creating the feature branch :-/ ... I'll have a look at how to squash that single commit - `git rebase master --interactive` is not showing that as one of the commits, for some reason

**Comment by madAndroid** [comment]
ahh.. there we go :) sorted!

**Comment by madAndroid** [comment]
@kevpl - does that look okay now? :)

**Comment by kevpl** [comment]
@madAndroid yep, looks good.  I'll submit for testing now.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
