### PR TITLE
(maint) Update license copyright

### PR DESCRIPTION
**Pull request by sschneid**

### CODE REVIEW

**Comment by anodelman** [comment]
retest this please

**Comment by kevpl** [comment]
@sschneid would you update the commit message itself with the `(maint)` prefix as well?

**Comment by anodelman** [comment]
It strikes me that this really doesn't need any testing.  Oh well.  Will merge upon commit message update.

**Comment by sschneid** [comment]
> Will merge upon commit message update.

I've updated, which I think will kick off another round of testing... :/

**Pull request merged**
