### PR TITLE
(MAINT) add /usr/local/bin to ssh env vars

### PR DESCRIPTION
**Pull request by kevpl**
ref #1405

### CODE REVIEW

**Comment by kevpl** [comment]
seems unrelated, kicking again.

@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by Iristyle** [comment]
Looks like this passed across the board... but see notes at https://github.com/puppetlabs/beaker/pull/1405#issuecomment-310791474 about it not quite doing what I had hoped for on `SLES11` for instance.  Looks like `~/.bashrc` requires changes to get desired behavior on `SLES11`

**Comment by kevpl** [comment]
this conversation has been sitting fallow between this PR, #1405, & #1406 for a very long time.

Since that's the case, it doesn't seem like a pressing issue, so I'm going to close these PRs.

**Pull request closed without merging**
