### PR TITLE
(BKR-879) beaker 3.0 gem audit

### PR DESCRIPTION
**Pull request by kevpl**

### CODE REVIEW

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
failure was based on Ruby 1.9, which we expect to fail with these changes. Removed 1.9 from the axis for now to test this further, re-kicking:

@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
was still using Ruby 1.9 😿 . Once more, with feeling!

@puppetlabs-jenkins retest this please

**Comment by tvpartytonight** [comment]
LGTM! 👍

**Pull request merged**
