### PR TITLE
(MAINT) Correcting method name in docs

### PR DESCRIPTION
**Pull request by timhughes**

### CODE REVIEW

**Comment by kevpl** [comment]
@timhughes good catch!  Would you update your git message, prefixing it with `(MAINT)`, so this can be classified correctly?

Thanks!  I'm :+1: other than the contributor change above, and I look forward to getting this merged & released!

**Comment by timhughes** [comment]
Is that what you mean or would you like me to make a new commit and rebase

**Comment by kevpl** [comment]
new commit and rebase, please.  Actually, internally, we usually amend the last commit for something like this.  But that does require a forced push, so whichever you'd prefer.

**Comment by timhughes** [comment]
done :-)

**Comment by kevpl** [comment]
perfect!  Thanks so much!

**Pull request merged**
