### PR TITLE
(BKR-1568) update pry-byebug dependency 3.4.2->3.6

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by smcelmurry** [comment]
test this please

**Comment by bastelfreak** [comment]
Hi @smcelmurry. I've no access to the travis logs. Could you paste them or let me know what failed / what jenkins actually did?

**Comment by smcelmurry** [comment]
@bastelfreak We're using ruby version `2.1.9` in the tests, causing this to fail. I'll update the pipeline and rekick this once that's live.

**Comment by bastelfreak** [comment]
Hey @smcelmurry, do you have an update for us? This is currently breaking beaker on latest stable ruby.

**Comment by smcelmurry** [comment]
@bastelfreak We just updated the ruby versions and reworked some of the pipeline. I'll rekick it now.

**Comment by smcelmurry** [comment]
retest this please

**Comment by smcelmurry** [comment]
retest this please

**Comment by smcelmurry** [comment]
retest this please

**Pull request merged**
