### PR TITLE
(BKR-528) Set ENV container docker

### PR DESCRIPTION
**Pull request by mmckinst**
See below relevant links:

* https://github.com/test-kitchen/kitchen-docker/pull/192
* https://github.com/test-kitchen/kitchen-docker/pull/216
* https://developerblog.redhat.com/2014/05/05/running-systemd-within-docker-container/

### CODE REVIEW

**Comment by mmckinst** [comment]
ticket re-opened about the issue: https://tickets.puppetlabs.com/browse/BKR-528

**Comment by kevpl** [comment]
@mmckinst thanks for the fix. Would you add a simple spec test so that we don't break this going forward?

If you would also update your git commit with a prefix referencing the ticket `(BKR-528)`, this will match our [contributor guidelines](https://github.com/puppetlabs/beaker/blob/master/CONTRIBUTING.md), and we can get it merged.

**Comment by mmckinst** [comment]
@kevpl all set!

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Pull request merged**
