### PR TITLE
(QENG-5106) Revert "Update Beaker to support amazon as a platform"

### PR DESCRIPTION
**Pull request by kevpl**
### Out Of Band Pre-Merge Tasks

- [ ] a passing Amazon pipeline using this ref to verify this won't break them

### CODE REVIEW

**Comment by mchllweeks** [comment]
retest this please

**Comment by ferglor** [comment]
retest this please

**Comment by mchllweeks** [comment]
retest this please

**Comment by mchllweeks** [comment]
retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
