### PR TITLE
(BKR-1472) Unwrap Markdown

### PR DESCRIPTION
**Pull request by Dakta**
Hard wrapping on Markdown text was applied inconsistently between (and within) docs; all hard wrapping has been removed.

Split from #1513

### CODE REVIEW

**Comment by kevpl** [comment]
What's the advantage to completely unwrapping as opposed to having a limit?

Other than that, I'm fine with this. It'll need to be rebased to be ready to merge though.

**Comment by Dakta** [comment]
There are pitfalls to hard-wrapping Markdown in particular:

- Though uncommon, it can lead to unexpected formatting outcomes. Especially when modifying the wrapping, where block-defining syntax can get wrapped onto a new line. For example, if an inline hyphen is hard-wrapped onto a new line it will break the paragraph by starting a list. Same for a number of other block-level formatting characters.
- Changes to line content require re-wrapping. While software tools can accomplish this, see above. Single-word changes that result in re-wrapping show extraneous whitespace changes in wrapped adjacent lines. In a long paragraph, this can result in dozens of lines modified for a single word change.
- Hard-wrapping of indented blocks requires re-indenting (not necessarily handled properly by generic tools), and can lead again to surprise formatting outcomes.
- Hard-wrapping without a standard line-length results in inconsistent raw formatting across and within files. If the hard-wrapping is longer than the developer's editor wrapping length, it can result in hanging lines. If it matches perfectly, the developer must check the wrapping to match it, because their editor's soft-wrapping will visually match the document's hard-wrapping. If it's shorter, the developer may not notice; if they apply hard wrapping it may not match.

While I'm opposed to hard wrapping, my preferences don't drive this project and this is a big change just for whitespace; I understand. At the least we should adopt hard-wrapping guidelines as part of the Markdown formatting doc so that things are more consistent moving forward.

**Comment by kevpl** [comment]
hehe, I preferred having a hard-wrap before this, but your simple argument in #1518 on it ([here unless it's moved around since then](https://github.com/puppetlabs/beaker/pull/1518/files#diff-9a67ecce54db708099f48cd19850f6d3R14)) convinced me, let alone all the points you make here.

I'm in favor of this, but it'll need to be rebased before it can be merged.

**Comment by Dakta** [comment]
Rebased and ready for a clean, fast-forward merge.

**Pull request merged**
