### PR TITLE
(BKR-1621) Add support for macOS Catalina

### PR DESCRIPTION
**Pull request by GabrielNagy**
...and be more permissive regarding OS X versions in exec.rb

### CODE REVIEW

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
this failure seems to be cause by an infrastructure issue that I believe we've gotten around at this point

@puppetlabs-jenkins retest this please

**Comment by GabrielNagy** [comment]
@puppetlabs-jenkins retest this please

**Comment by mihaibuzgau** [comment]
@puppetlabs-jenkins retest this please

**Comment by ciprianbadescu** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by GabrielNagy** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
