### PR TITLE
(BKR-327) Add support for EL7 to add_el_extras method

### PR DESCRIPTION
**Pull request by madAndroid**
Without this change, you cannot use the `add_el_extras` method for CentOS/RHEL 7 hosts

### CODE REVIEW

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
retest this please

**Comment by anodelman** [comment]
Failure unrelated to patch.

**Comment by anodelman** [comment]
Failure during testing:
```
 rpm -i http://mirrors.kernel.org/fedora-epel/7/e/x86_64/epel-release-7-5.noarch.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping http://mirrors.kernel.org/fedora-epel/7/e/x86_64/epel-release-7-5.noarch.rpm - transfer failed

ewlaig3wjcqwrpb.delivery.puppetlabs.net (centos7-64-1) executed in 0.18 seconds
Exited: 1
Failed: errored in add_repos
#<Beaker::Host::CommandFailure: Host 'ewlaig3wjcqwrpb.delivery.puppetlabs.net' exited with 1 running:
 rpm -i http://mirrors.kernel.org/fedora-epel/7/e/x86_64/epel-release-7-5.noarch.rpm
Last 10 lines of output were:
	curl: (22) The requested URL returned error: 404 Not Found
	error: skipping http://mirrors.kernel.org/fedora-epel/7/e/x86_64/epel-release-7-5.noarch.rpm - transfer failed>
```

**Comment by anodelman** [comment]
Will close out next week due to inactivity.

**Comment by madAndroid** [comment]
I just don't have enough cycles to revisit this, I'm afraid .. the changes tested okay locally, not sure why the failures occurred in CI. I've implemented an alternative solution in my own environments; perhaps someone else will pick this up at some point.

**Pull request closed without merging**
