### PR TITLE
(maint) Extra quoting for Windows versions.txt

### PR DESCRIPTION
**Pull request by Iristyle**
- Adds quotes around the "if exist path type path" command passed to
   cmd.exe, which also requires that quotes around filenames have
   their quoting escaped

### CODE REVIEW

**Comment by Iristyle** [comment]
@glennsarti this should fix the issue we've observed when retrieving the 32-bit agents versions.txt inside 64-bit Windows.  Still not sure why the `(x86)` is causing problems....

**Comment by glennsarti** [comment]
Reference in MODULES-3449

**Comment by Iristyle** [comment]
We should make sure that we trigger some manual runs against this PR prior to merging.  For whoever ends up doing that @puppetlabs/windows, please put the output from the runs here. We want all 3 combos:

* 64-bit agent on 64-bit OS
* 32-bit agent on 64-bit OS (this is the problematic one prior to this commit)
* 32-bit agent on 32-bit OS

**Comment by Iristyle** [comment]
Running with this change everything looks good now - this can be merged @glennsarti / @kevpl 

### 32-bit agent on 64-bit OS

```
TEST_TARGET=windows2012r2-6432a BEAKER_VERSION=git://github.com/Iristyle/beaker#maint/master/log-windows-versions-fix bundle exec rake ci:test:aio TESTS=tests/resource/scheduled_task/should_modify.rb SHA=0ac41b7e5e8f6d810503dd516a588f7d5111a3d8
```

```
C:\cygwin64\home\Administrator>start /w msiexec.exe /i "C:\PROGRA~3\puppet-agent-x86.msi" /qn /L*V C:\Windows\TEMP\install-puppet-2016-06-21_16.47.42.log PUPPET_AGENT_STARTUP_MODE=Manual

...

q8yxgpx3vtxayyp.delivery.puppetlabs.net (windows2012r2-6432-1) 16:47:57$ cmd.exe /c "if exist \"%ProgramFiles%\Puppet Labs\puppet\misc\versions.txt\" type \"%ProgramFiles%\Puppet Labs\puppet\misc\versions.txt\""

  q8yxgpx3vtxayyp.delivery.puppetlabs.net (windows2012r2-6432-1) executed in 0.07 seconds

  q8yxgpx3vtxayyp.delivery.puppetlabs.net (windows2012r2-6432-1) 16:47:57$ cmd.exe /c "if exist \"%ProgramFiles(x86)%\Puppet Labs\puppet\misc\versions.txt\" type \"%ProgramFiles(x86)%\Puppet Labs\puppet\misc\versions.txt\""
    puppet_for_the_win 4.5.2-0-gae1821b
    facter 3.1.8-41-gfbc52a0
    hiera 3.2.0-5-g9c8b977
    mcollective 2.8.8-25-g65a2cae
    puppet 4.5.2-121-ga0f3f55
    pxp-agent 1.1.3-46-g90375dc
    sys 2.1.9.0-x86-0-g096192b

  q8yxgpx3vtxayyp.delivery.puppetlabs.net (windows2012r2-6432-1) executed in 0.09 seconds
```

### 64-bit agent on 64-bit OS

```
TEST_TARGET=windows2012r2-64a BEAKER_VERSION=git://github.com/Iristyle/beaker#maint/master/log-windows-versions-fix bundle exec rake ci:test:aio TESTS=tests/resource/scheduled_task/should_modify.rb SHA=0ac41b7e5e8f6d810503dd516a588f7d5111a3d8
```

```
C:\cygwin64\home\Administrator>start /w msiexec.exe /i "C:\PROGRA~3\puppet-agent-x64.msi" /qn /L*V C:\Windows\TEMP\install-puppet-2016-06-21_17.10.43.log PUPPET_AGENT_STARTUP_MODE=Manual

...

ulb62qpcqblmqep.delivery.puppetlabs.net (windows2012r2-64-1) 17:10:55$ cmd.exe /c "if exist \"%ProgramFiles%\Puppet Labs\puppet\misc\versions.txt\" type \"%ProgramFiles%\Puppet Labs\puppet\misc\versions.txt\""
    puppet_for_the_win 4.5.2-0-gae1821b
    facter 3.1.8-41-gfbc52a0
    hiera 3.2.0-5-g9c8b977
    mcollective 2.8.8-25-g65a2cae
    puppet 4.5.2-121-ga0f3f55
    pxp-agent 1.1.3-46-g90375dc
    sys 2.1.9.0-x64-0-ga5963ea

  ulb62qpcqblmqep.delivery.puppetlabs.net (windows2012r2-64-1) executed in 0.08 seconds

  ulb62qpcqblmqep.delivery.puppetlabs.net (windows2012r2-64-1) 17:10:55$ cmd.exe /c "if exist \"%ProgramFiles(x86)%\Puppet Labs\puppet\misc\versions.txt\" type \"%ProgramFiles(x86)%\Puppet Labs\puppet\misc\versions.txt\""

  ulb62qpcqblmqep.delivery.puppetlabs.net (windows2012r2-64-1) executed in 0.09 seconds
```


### 32-bit agent on 32-bit OS

```
TEST_TARGET=windows10ent-32a BEAKER_VERSION=git://github.com/Iristyle/beaker#maint/master/log-windows-versions-fix bundle exec rake ci:test:aio TESTS=tests/resource/scheduled_task/should_modify.rb SHA=0ac41b7e5e8f6d810503dd516a588f7d5111a3d8
```

```
C:\cygwin\home\Administrator>start /w msiexec.exe /i "C:\PROGRA~2\puppet-agent-x86.msi" /qn /L*V C:\Windows\TEMP\install-puppet-2016-06-21_17.15.06.log PUPPET_AGENT_STARTUP_MODE=Manual

...

yb04ohhb9g5krft.delivery.puppetlabs.net (windows10ent-32-1) 17:15:25$ cmd.exe /c "if exist \"%ProgramFiles%\Puppet Labs\puppet\misc\versions.txt\" type \"%ProgramFiles%\Puppet Labs\puppet\misc\versions.txt\""
    puppet_for_the_win 4.5.2-0-gae1821b
    facter 3.1.8-41-gfbc52a0
    hiera 3.2.0-5-g9c8b977
    mcollective 2.8.8-25-g65a2cae
    puppet 4.5.2-121-ga0f3f55
    pxp-agent 1.1.3-46-g90375dc
    sys 2.1.9.0-x86-0-g096192b

  yb04ohhb9g5krft.delivery.puppetlabs.net (windows10ent-32-1) executed in 0.08 seconds

  yb04ohhb9g5krft.delivery.puppetlabs.net (windows10ent-32-1) 17:15:25$ cmd.exe /c "if exist \"%ProgramFiles(x86)%\Puppet Labs\puppet\misc\versions.txt\" type \"%ProgramFiles(x86)%\Puppet Labs\puppet\misc\versions.txt\""

  yb04ohhb9g5krft.delivery.puppetlabs.net (windows10ent-32-1) executed in 0.08 seconds
```

**Pull request merged**
