### PR TITLE
Fix typo ptry => pty, sudo failing on el7

### PR DESCRIPTION
**Pull request by davemcdonnell**

### CODE REVIEW

**Comment by kevpl** [comment]
@davemcdonnell, please update your commit message to have an issue referenced (create one if needed), and we look forward to getting this fix in!

**Comment by davemcdonnell** [comment]
Added issue https://tickets.puppetlabs.com/browse/BKR-245 and referenced in commit

**Comment by kevpl** [comment]
@davemcdonnell awesome, thanks. I'll kick off automated testing, and hopefully we'll get this in today.

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Pull request merged**
