### PR TITLE
(QENG-4068) Remove unnecessary gem documentation dependencies

### PR DESCRIPTION
**Pull request by tvpartytonight**
These gems are not necessary for beaker itself, and they do not need to
be specified in the the gemspec.

### CODE REVIEW

**Comment by kevpl** [comment]
From our conversation, it seemed like these were still necessary as long as we support Ruby 1.9, yeah?

**Comment by tvpartytonight** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@tvpartytonight per our discussion, you were looking to do some last minute verification. Let us know when that's done, and we'll look at merging this.

**Comment by tvpartytonight** [comment]
@kevpl this should be ready for merge now; the jenkins job is now defined and will kick off prior the Master Status job, so merging this in before 4:24 pm Tuesday July 19th would be good verification that this is working.

**Pull request merged**
