### PR TITLE
(BKR-321) Added LXC hypervisor support for beaker

### PR DESCRIPTION
**Pull request by ashish1099**
Added LXC hypervisor for beaker. We have been using LXC from past 1 year have been really helpful in our environment. I had raised PR earlier somehow forgot to keep track of it

### CODE REVIEW

**Comment by kevpl** [comment]
Hi @ashish1099! Sorry for the delay in getting back to you on this. In our conversation in #985, we determined that we'd rather not make people include more gems at this point than are needed, and are looking to find ways to downsize our footprint as well. For this reason, unless we find a workaround to only optionally install these gems, we're not looking to merge PRs like this one.

In that PR, we suggested that the submitter potentially maintain a fork of Beaker as THE LXC fork, and that if they'd like, we can link to them.  Would you like to maintain LXC support for the Beaker community by having us point to your fork as the one to use if you'd like to use the LXC hypervisor?

**Comment by kevpl** [comment]
last comment still current

**Comment by ashish1099** [comment]
@kevpl I'm OK with that.

**Comment by kevpl** [comment]
Thanks @ashish1099! I'll be submitting a small PR to update our docs later today. When I do this, I'll reference that one from here, and then close this PR.  Feel free to re-open this PR, or open or re-open a new ticket if you have any questions about this or anything involved with it.  Thanks!

**Comment by kevpl** [comment]
Created #1136. Since that's the case, I'll close this PR.

**Pull request closed without merging**
