### PR TITLE
(BKR-1011) Fix Windows group_get error detection

### PR DESCRIPTION
**Pull request by Iristyle**
- The existing mechanism is tightly coupled to English / ASCII output
   and should instead use exit codes.

   Fix both the PowerShell and CMD hosts.

   Add a new acceptance test so that this can be validated on a
   non-English Windows host (for instance Japanse Windows 2012R2
   template win-2012r2-ja-x86_64)

### CODE REVIEW

**Comment by Iristyle** [comment]
Builds on #1293

**Comment by MosesMendoza** [comment]
👍 . The PE upgrade suite tests failed on one cell triggering the check failure above. It appears unrelated.

```
 Failed to connect to qpgv6b0z2w42zkx.delivery.puppetlabs.net port 8140: Connection refused
```

**Comment by Iristyle** [comment]
@puppetlabs-jenkins retest this please

**Comment by Iristyle** [comment]
@puppetlabs-jenkins retest this please

**Comment by Iristyle** [comment]
@kevpl this now has the green sign of approval as well... merge 'er up.

**Pull request merged**
