### PR TITLE
Feature/libvirt options

### PR DESCRIPTION
**Pull request by sathlan**
Those patches enable one to specify:

    vagrant_cpus: 2
  libvirt:
    uri: qemu+ssh://root@blah/system
    management_network_name: my_vagrant

### CODE REVIEW

**Comment by kevpl** [comment]
@sathlan is there a BKR ticket for this change? If not, then a `(MAINT)` prefix should be added to all of the commits in the PR history.

Before this change can be merged, there'll need to be tests and docs added for it. Let us know if you have any questions about adding these.

**Comment by kevpl** [comment]
last comment still current

**Comment by kevpl** [comment]
last comment still current

**Comment by sathlan** [comment]
Made a proper feature request and pull request there https://github.com/puppetlabs/beaker/pull/1222

**Comment by kevpl** [comment]
OK, I'll close this issue, and we'll discuss your changes there then

**Pull request closed without merging**
