### PR TITLE
Fix `BEAKER_provision=no` workflow

### PR DESCRIPTION
**Pull request by joshuaspence**
Fixes BKR-1111 and BKR-494.

### CODE REVIEW

**Comment by pinkypie** [comment]
@puppetlabs-jenkins retest this please

**Comment by mchllweeks** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@joshuaspence reading the tickets for this issue, it sounds like the real problem here is that the host preservation functionality between runs isn't putting the correct info into the file for the next run.

It seems that this solution takes away people's ability to run beaker without provisioning Systems Under Test (SUTs), which is a valid use-case, in order to allow your second run to work (although it has given up on not provisioning those SUTs). Am I mis-reading your work here? If not, then this isn't going to work for beaker as a valid solution to the issue.

**Comment by mchllweeks** [comment]
Last comment still current.

**Comment by joshuaspence** [comment]
I think I know a better fix.

**Comment by joshuaspence** [comment]
See puppetlabs/beaker-vagrant#13 instead.

**Pull request closed without merging**
