### PR TITLE
(BKR-847) Fix with_host_stubbed_on

### PR DESCRIPTION
**Pull request by johnduarte**
Prior to this commit, the `@teardown_procs` value was not being created
to handle the teardown referenced by calling `stub_hosts_on` within
`with_host_stubbed_on`. This commit removes the reference to the method
and adds in the desired code directly.

### CODE REVIEW

**Comment by johnduarte** [comment]
This test has been tested against the acceptance tests for the [wsus-client](https://github.com/puppetlabs/puppetlabs-wsus_client) module in order to confirm the desired behavior.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by tvpartytonight** [comment]
@johnduarte could you change your commit and PR message to more accurately reflect the reason for this change is that teardowns are not usable by beaker-rspec?

**Comment by tvpartytonight** [comment]
I stopped the job, as the update was just an improved commit message and comments in the code.

**Pull request merged**
