### PR TITLE
(BKR-321) LXC container support

### PR DESCRIPTION
**Pull request by qvicksilver**
Adds support for running beaker tests in LXC containers.

### CODE REVIEW

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by qvicksilver** [comment]
Any hints on whats failing this time?

**Comment by electrical** [comment]
Ran the tests locally and pass but i had to install several system libraries to be able to install the required ruby-lxc gem
If those system libs are not available it might be the cause for failure.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by qvicksilver** [comment]
Let me know if there is anything I can or need to do here.

**Comment by developerinlondon** [comment]
@qvicksilver have you tried merging the latest master into it for resolving any conflicts?

**Comment by qvicksilver** [comment]
@developerinlondon tried that, merging works fine but then the tests fail on 1.9.3 because of: http://comments.gmane.org/gmane.comp.cloud.openstack.devel/69682 and then I break contribution protocol...

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@qvicksilver, we've run into the same issues that @electrical was reporting about system packages not being installed (after doing some work for the gem itself).

At this point, we're looking to minimize impact on our users in general.  This change means that most of our users will have to install packages for a hypervisor they don't use.  Is it reasonable to be able to get this support into beaker without these packages?

**Comment by kevpl** [comment]
last comment is current

**Comment by qvicksilver** [comment]
@kevpl limiting impact to users sounds very reasonable. Would placing the lxc gem dependencies in an optional group in the Gemfile be an option?

It could most likely be implemented using the lxc cli tools, not sure how much work would be needed.

**Comment by kevpl** [comment]
@qvicksilver I think having an optional group in the Gemfile could be a good option at this point.  In creating the optional group, please make sure to set a pattern similar to `hypervisor-lxc`, just so we can know that these requirements are for a specific hypervisor.

My only other note about this would be to make sure in the initializer to catch the gem not being able to load, put out some nice messaging about how they have to install the named gem group, and `raise` up outta there, for the case when someone tries to use this hypervisor but hasn't installed the dependencies.

**Comment by qvicksilver** [comment]
Moved the ruby-lxc dependency to its own optional group and fixed the initializer.

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by kevpl** [comment]
@qvicksilver my apologies, the error that the Jenkins job threw was this:

    Using /usr/local/rvm/gems/ruby-1.9.3-p484
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dependency.rb:54:in `block in initialize': undefined method `to_sym' for {:optional=>true}:Hash (NoMethodError)
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dependency.rb:54:in `map'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dependency.rb:54:in `initialize'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dsl.rb:74:in `new'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dsl.rb:74:in `gem'
       /var/lib/jenkins/workspace/qe_beaker_unit-rb_rspec/ruby/1.9.3-p484/Gemfile:23:in `block in eval_gemfile'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dsl.rb:166:in `group'
       /var/lib/jenkins/workspace/qe_beaker_unit-rb_rspec/ruby/1.9.3-p484/Gemfile:22:in `eval_gemfile'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `instance_eval'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `eval_gemfile'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/dsl.rb:10:in `evaluate'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/definition.rb:25:in `build'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler.rb:155:in `definition'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/cli/install.rb:78:in `run'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
       /usr/local/rvm/gems/ruby-1.9.3-p484/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
       /usr/local/rvm/gems/ruby-1.9.3-p484/bin/bundle:23:in `load'
       /usr/local/rvm/gems/ruby-1.9.3-p484/bin/bundle:23:in `<main>'
       /usr/local/rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `eval'
       /usr/local/rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'
    There was an error in your Gemfile, and Bundler cannot continue.

**Comment by qvicksilver** [comment]
@kevpl no worries, haven't really had time to work with this anyway. Anyhow this seems to happen due to bundler only supporting optional groups from version 1.10.x. I could of course make the optional group available only for supported bundler versions but I get the feeling that things are becoming rather unintuitive.
Not really sure how to proceed here, or if at all.

**Comment by kevpl** [comment]
@qvicksilver you're right, this is definitely becoming a little more difficult.  At this point, my opinion would be that you maintain a fork of beaker, and we can link to it as our best way to use LXC hypervisors in our docs.  Would that work for you?

We want to support a template for making hypervisor beaker-libraries, but we're not there yet.  That would be my longer-term suggestion if we had the infrastructure setup for you, or where I would suggest we move to once that infrastructure is there.

**Comment by kevpl** [comment]
last comment is still current. If this is not commented on or touched in a week, it'll be closed due to inactivity. Please let me know if you have any questions about this.

**Comment by qvicksilver** [comment]
@kevpl sorry I haven't replied sooner, newborn kids do however reduce keyboard-time apparently. Back to the matter at hand, seems like beaker LXC fork is not being used very much at my workplace anymore. If that continues it is very likely that I won't have time to maintain it anymore, with that being said you are free to link to it if you please.

If usage takes off and your templates plans get realized I'll probably be back with another PR. Thanks for the patience and support!

**Pull request closed without merging**
