### PR TITLE
(maint) add --no-gpg-check to install_package on sles

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by speedofdark** [comment]
Could you please include a brief reason why this change is needed? Thanks!

**Comment by caseywilliams** [comment]
Ah, I see now. Our `localmirror-os` repo is unsigned and the installation of sqlite3-devel fails on (at least) SLES 11 during tests without this change.

**Comment by caseywilliams** [comment]
This will need to be merged and beaker will need to be released before any of puppet-agent CI can pass again

**Comment by caseywilliams** [comment]
fwiw, it may make (more?) sense to address this in our image templates: https://github.com/loopinu/puppetlabs-packer/blob/947d96c39ceab569b14446ca979384ac8be13679/manifests/modules/packer/manifests/vsphere/repos.pp#L276-L281

**Comment by caseywilliams** [comment]
Ok, I do think it would be better to address this in the packer template, since that would allow us to keep checking gpg keys for everything else.

**Comment by gimmyxd** [comment]
closing this in favor of https://github.com/puppetlabs/puppetlabs-packer/pull/424

**Pull request closed without merging**
