### PR TITLE
(BKR-1423) Re-add ability to change SSH settings

### PR DESCRIPTION
**Pull request by trevor-vaughan**
This patch restores the ability to modify system SSH settings from the
`ssh` configuration hash in the nodesets.

The hash is merged with the configuration that is dropped into the
temporary file from Vagrant if present and simply used as-is otherwise.

BRK-1423 #close

### CODE REVIEW

**Comment by kevpl** [comment]
@trevor-vaughan please add a spec test so that we don't mess up your change in the future.

Also, would you refer us to what change pulled it out?

**Comment by trevor-vaughan** [comment]
@kevpl Honestly, I just know that it worked at one point and didn't work at some point in the future. If you can point me at where the existing test are, I'd be happy to update them if they have the hooks in place.

**Comment by trevor-vaughan** [comment]
Looked through the test code and all of it seems to stub out `connection`. Any advice on how to actually set the `self` parameters in a way that the code will pick it up?

**Comment by kevpl** [comment]
I assume that you don't stub out connection and that the code will automatically pick up the right method. In terms of the host details needed for that, I would setup a describe block for the connection method, call connection with the `SshConnection` object stubbed out, and see what sorts of things it's complaining about, if anything.

It seems like perhaps the `SshConnection` constructor will list all the things you'll need, but if you use the `anything` spec method to allow those to be called with anything as a parameter, those things might not be needed.

**Comment by kevpl** [comment]
last comment is still current

**Comment by kevpl** [comment]
last comment is still current. If no movement is made on this in a week, we'll close it due to inactivity.

**Comment by kevpl** [comment]
closing due to inactivity. Please re-open once some movement has been made.

**Pull request closed without merging**
