### PR TITLE
[BKR-358] Add acceptance tests for hosts helpers

### PR DESCRIPTION
**Pull request by rick**
Adds acceptance tests for hosts helpers.

Detailed commit history and discussion can be found at #930

/cc @puppetlabs/beaker

### CODE REVIEW

**Comment by anodelman** [comment]
@rick the deb7 failures reoccurred.

**Comment by rick** [comment]
At least it's consistent, while transient :-)

On Wed, Sep 23, 2015 at 1:07 PM, alice nodelman <notifications@github.com>
wrote:

> @rick <https://github.com/rick> the deb7 failures reoccurred.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/beaker/pull/965#issuecomment-142683419>.
>



-- 

*PuppetConf 2015 <http://2015.puppetconf.com/> is coming to Portland,
Oregon! Join us October 5-9.*
*Register now to take advantage of the Final Countdown discount
<https://www.eventbrite.com/e/puppetconf-2015-october-5-9-register-now-its-the-final-countdown-tickets-13115894995?discount=FinalCountdown>
*
*—**save $149!*

**Comment by kevpl** [comment]
@rick it looks like conversation is still going down in #930.  Are you looking to merge _some_ of that up here, and then finish the rest there, or should this be closed until that conversation is resolved?

**Comment by rick** [comment]
I don't have a strong opinion on whether to keep this open or close it.  The resolution of various transient test failures will be completed in #930 and some squashed version will end up here or in another PR; I'm open to either way.

**Comment by kevpl** [comment]
Since that's the case, I'd prefer there only be one open PR to lessen distractions until that work is done. I'm closing this, but obviously, feel free to either re-open this or open a new PR once the work is done in #930.

**Pull request closed without merging**
